CREATE TABLE [dbo].[AGGIORNAMENTO_DA_INVIARE] (
    [PROG]       INT          IDENTITY (1, 1) NOT NULL,
    [NEG]        VARCHAR (10) NOT NULL,
    [TABELLA]    VARCHAR (50) NOT NULL,
    [OPERAZIONE] VARCHAR (50) CONSTRAINT [DF_AGGIORNAMENTO_DA_INVIARE_OPERAZIONE] DEFAULT ('UPDATE') NOT NULL,
    [DOCXML]     XML          NOT NULL,
    CONSTRAINT [PK_DATI_PER_NEGOZI] PRIMARY KEY CLUSTERED ([PROG] ASC)
);

