CREATE TABLE [dbo].[ALLERGENE] (
    [ID_ALLERGENE] INT           IDENTITY (1, 1) NOT NULL,
    [DESCRIZIONE]  VARCHAR (200) NOT NULL,
    CONSTRAINT [PK_ALLERGENI] PRIMARY KEY CLUSTERED ([ID_ALLERGENE] ASC)
);

