CREATE TABLE [dbo].[ARTICOLO_INGREDIENTE] (
    [ID_ARTICOLO]    INT NOT NULL,
    [ID_INGREDIENTE] INT NOT NULL,
    CONSTRAINT [PK_ARTICOLO_INGREDIENTI] PRIMARY KEY CLUSTERED ([ID_ARTICOLO] ASC, [ID_INGREDIENTE] ASC)
);

