CREATE TABLE [dbo].[ARTICOLO_LINGUA] (
    [ID_ARTICOLO] INT   NOT NULL,
    [ID_LINGUA]   INT   NOT NULL,
    [DESCRIZIONE] NTEXT NOT NULL,
    CONSTRAINT [PK_ARTICOLO_LINGUAù] PRIMARY KEY CLUSTERED ([ID_ARTICOLO] ASC, [ID_LINGUA] ASC)
);

