CREATE TABLE [dbo].[ARTICOLO_ALLERGENE] (
    [ID_ARTICOLO]  INT NOT NULL,
    [ID_ALLERGENE] INT NOT NULL,
    CONSTRAINT [PK_ARTICOLO_ALLERGENI] PRIMARY KEY CLUSTERED ([ID_ARTICOLO] ASC, [ID_ALLERGENE] ASC)
);

