CREATE TABLE [dbo].[BASKET_PAGAMENTO] (
    [ID_BASKET]      INT          NOT NULL,
    [TIPO_PAGAMENTO] VARCHAR (10) NOT NULL,
    [IMPORTO]        MONEY        NOT NULL,
    CONSTRAINT [PK_BASKET_PAGAMENTO] PRIMARY KEY CLUSTERED ([ID_BASKET] ASC, [TIPO_PAGAMENTO] ASC)
);

