CREATE TABLE [dbo].[BASKET_TEMPORANEO] (
    [CODICE_NEGOZIO] VARCHAR (10)  NOT NULL,
    [CODICE_BASKET]  VARCHAR (250) NOT NULL,
    [EAN]            VARCHAR (13)  NOT NULL,
    [QUANTITA]       INT           NOT NULL,
    [PREZZOTOTALE]   MONEY         NOT NULL,
    CONSTRAINT [PK_BASKET_TEMPORANEO] PRIMARY KEY CLUSTERED ([CODICE_NEGOZIO] ASC, [CODICE_BASKET] ASC, [EAN] ASC)
);

