CREATE TABLE [dbo].[CANALE_VENDITA] (
    [COD_NEGOZIO]          VARCHAR (10)  NOT NULL,
    [COD_CANALE_VENDITA]   VARCHAR (10)  NOT NULL,
    [DES_CANALE_VENDITA]   VARCHAR (500) NOT NULL,
    [SIGLA_CANALE_VENDITA] VARCHAR (25)  NOT NULL,
    CONSTRAINT [PK_CANALE_VENDITA] PRIMARY KEY CLUSTERED ([COD_NEGOZIO] ASC, [COD_CANALE_VENDITA] ASC)
);

