CREATE TABLE [dbo].[CATEGORIA_old] (
    [ID_CATEGORIA]          INT           NOT NULL,
    [DESCRIZIONE_CATEGORIA] VARCHAR (250) CONSTRAINT [DF_CATEGORIA_DESCRIZIONE_CATEGORIA_old] DEFAULT ('') NOT NULL,
    [IMMAGINE]              VARCHAR (250) CONSTRAINT [DF_CATEGORIA_IMMAGINE_old] DEFAULT ('') NOT NULL,
    [STATUS]                VARCHAR (10)  CONSTRAINT [DF_CATEGORIA_STATUS_old] DEFAULT ('V') NOT NULL,
    [ORDINE]                INT           CONSTRAINT [DF_CATEGORIA_ORDINE_old] DEFAULT ((0)) NOT NULL,
    [VISUALIZZA]            CHAR (1)      CONSTRAINT [DF_CATEGORIA_VISUALIZZA_old] DEFAULT ('S') NOT NULL,
    CONSTRAINT [PK_CATEGORIA_old] PRIMARY KEY CLUSTERED ([ID_CATEGORIA] ASC)
);

