CREATE TABLE [dbo].[GIACENZA] (
    [CODICE_NEGOZIO] VARCHAR (10)    NOT NULL,
    [EAN]            VARCHAR (13)    NOT NULL,
    [ID_ARTICOLO]    INT             CONSTRAINT [DF_GIACENZA_ID_ARTICOLO] DEFAULT ((0)) NOT NULL,
    [GIACENZA]       DECIMAL (18, 3) CONSTRAINT [DF_GIACENZA_GIACENZA] DEFAULT ((0)) NOT NULL,
    [RIORDINO]       DECIMAL (18, 3) CONSTRAINT [DF_GIACENZA_RIORDINO] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_GIACENZA] PRIMARY KEY CLUSTERED ([CODICE_NEGOZIO] ASC, [EAN] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_IdArticolo]
    ON [dbo].[GIACENZA]([ID_ARTICOLO] ASC);


GO
-- =============================================
-- Author:		Delpiano
-- Create date: 02-02-2017
-- Description:	per ogni giacenza modificata richiamo la stored 
-- che ne memorizza i dati da inviare ai server locali
-- =============================================
CREATE TRIGGER [dbo].[TRG_UPD_GIACENZA] 
   ON  [dbo].[GIACENZA]
   FOR INSERT,UPDATE
AS 
BEGIN

	SET NOCOUNT ON;

	IF EXISTS(SELECT * FROM APP_SETUP WHERE CHIAVE = 'STOP_TRIGGER_ALLINEAMENTO' AND VALORE = 'SI')
	BEGIN
		GOTO FINE
	END

	DECLARE @KEY INT

	DECLARE CUR CURSOR LOCAL FOR
		SELECT EAN FROM INSERTED

	OPEN CUR

	FETCH NEXT FROM CUR INTO @KEY

	WHILE @@FETCH_STATUS = 0 BEGIN

		EXEC PRC_AGGIORNAMENTO_DA_INVIARE_INSERT @KEY, 'GIACENZA'
		FETCH NEXT FROM CUR INTO @KEY
	END

	CLOSE CUR
	DEALLOCATE CUR
	FINE:

END