CREATE TABLE [dbo].[NEGOZIO] (
    [CODICE_NEGOZIO]  VARCHAR (10)  NOT NULL,
    [RAGIONE_SOCIALE] VARCHAR (500) NOT NULL,
    [STATUS]          VARCHAR (10)  CONSTRAINT [DF_NEGOZIO_STATUS] DEFAULT ('V') NOT NULL,
    [COD_CURRENCY]    CHAR (3)      NULL,
    CONSTRAINT [PK_NEGOZIO] PRIMARY KEY CLUSTERED ([CODICE_NEGOZIO] ASC)
);

