CREATE TABLE [dbo].[PROGRESSIVO] (
    [CODICE_NEGOZIO] VARCHAR (10) NOT NULL,
    [CODICE]         VARCHAR (50) NOT NULL,
    [PROGR]          INT          NOT NULL,
    CONSTRAINT [PK_PROGRESSIVO] PRIMARY KEY CLUSTERED ([CODICE_NEGOZIO] ASC, [CODICE] ASC)
);

