CREATE TABLE [dbo].[REPARTO_UTENTI] (
    [ID]            INT           IDENTITY (1, 1) NOT NULL,
    [IDREPARTO]     INT           NOT NULL,
    [CODICE_UTENTE] VARCHAR (30)  NOT NULL,
    [DESCRIZIONE]   VARCHAR (250) NOT NULL,
    [COLORE]        VARCHAR (25)  NOT NULL,
    [STATUS]        VARCHAR (10)  NULL,
    CONSTRAINT [PK_REPARTO_UTENTI] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_IDREPARTO_CODICE_UTENTE]
    ON [dbo].[REPARTO_UTENTI]([IDREPARTO] ASC, [CODICE_UTENTE] ASC);

