CREATE TABLE [dbo].[REPARTO] (
    [IDREPARTO]            INT           IDENTITY (1, 1) NOT NULL,
    [CODICE_NEGOZIO]       VARCHAR (10)  NOT NULL,
    [DESCRIZIONEREPARTO]   VARCHAR (500) NOT NULL,
    [NOMESTAMPANTECOMANDA] VARCHAR (250) NOT NULL,
    [DESCRIZIONECORTA]     VARCHAR (25)  NOT NULL,
    [STATUS]               VARCHAR (10)  NULL,
    [VISUALIZZA]           BIT           NOT NULL,
    CONSTRAINT [PK_REPARTO] PRIMARY KEY CLUSTERED ([IDREPARTO] ASC)
);

