CREATE TABLE [dbo].[SCONTRINATO_TESTATA_old] (
    [CODICE_NEGOZIO] VARCHAR (10) NOT NULL,
    [DATA]           CHAR (8)     NOT NULL,
    [ORA]            CHAR (6)     NOT NULL,
    [CASSA]          INT          NOT NULL,
    [SCONTRINO]      INT          NOT NULL,
    [ID_PROVENIENZA] CHAR (3)     NOT NULL,
    [ID_BASKET]      INT          NOT NULL,
    [STAMPATO]       CHAR (1)     NOT NULL,
    [PAGATO]         CHAR (1)     NOT NULL,
    [TOTALE]         MONEY        NOT NULL,
    [INVIATO]        CHAR (1)     CONSTRAINT [DF_SCONTRINATO_TESTATA_INVIATO] DEFAULT ('N') NOT NULL,
    [CODICE_UTENTE]  VARCHAR (30) CONSTRAINT [DF_SCONTRINATO_TESTATA_CODICE_UTENTE] DEFAULT ('') NOT NULL,
    [RINCARO]        MONEY        DEFAULT ((0)) NULL,
    CONSTRAINT [PK_SCONTRINATO_TESTATA_old] PRIMARY KEY CLUSTERED ([DATA] ASC, [ORA] ASC, [CASSA] ASC, [SCONTRINO] ASC, [CODICE_NEGOZIO] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX_ID_BASKET]
    ON [dbo].[SCONTRINATO_TESTATA_old]([ID_BASKET] ASC);

