CREATE TABLE [dbo].[SCONTRINATO_RIGA_old] (
    [CODICE_NEGOZIO]  VARCHAR (10)   NOT NULL,
    [DATA]            CHAR (8)       NOT NULL,
    [ORA]             CHAR (6)       NOT NULL,
    [CASSA]           INT            NOT NULL,
    [SCONTRINO]       INT            NOT NULL,
    [RIGA]            INT            NOT NULL,
    [EAN]             VARCHAR (13)   NOT NULL,
    [PREZZO]          MONEY          NOT NULL,
    [QTA]             DECIMAL (8, 3) CONSTRAINT [DF_SCONTRINATO_RIGA_QTA] DEFAULT ((1)) NOT NULL,
    [REPARTO_VENDITA] VARCHAR (1)    CONSTRAINT [DF_SCONTRINATO_RIGA_REPARTO_VENDITA] DEFAULT ('') NOT NULL,
    [LOTTO_VENDITA]   VARCHAR (1)    CONSTRAINT [DF_SCONTRINATO_RIGA_LOTTO_VENDITA] DEFAULT ('') NOT NULL,
    [PERC_SCONTO]     DECIMAL (6, 3) CONSTRAINT [DF_SCONTRINATO_RIGA_PERC_SCONTO] DEFAULT ((0)) NOT NULL,
    [VALORE_SCONTO]   MONEY          CONSTRAINT [DF_SCONTRINATO_RIGA_VALORE_SCONTO] DEFAULT ((0)) NOT NULL,
    [SCONTO_ESPOSTO]  CHAR (1)       CONSTRAINT [DF_SCONTRINATO_RIGA_SCONTO_ESPOSTO] DEFAULT ('N') NOT NULL,
    CONSTRAINT [PK_SCONTRINATO_RIGA_old] PRIMARY KEY CLUSTERED ([DATA] ASC, [ORA] ASC, [CASSA] ASC, [SCONTRINO] ASC, [CODICE_NEGOZIO] ASC, [RIGA] ASC)
);

