CREATE TABLE [dbo].[SCONTRINATO_TESTATA] (
    [ID_SCONTRINATO] INT          IDENTITY (1, 1) NOT NULL,
    [DATA_CREAZIONE] DATETIME     NOT NULL,
    [CODICE_NEGOZIO] VARCHAR (10) NOT NULL,
    [CASSA]          INT          NOT NULL,
    [SCONTRINO]      INT          NOT NULL,
    [ID_COMANDA]     INT          NOT NULL,
    [STAMPATO]       BIT          NOT NULL,
    [PAGATO]         BIT          NOT NULL,
    [TOTALE]         MONEY        NOT NULL,
    [CODICE_UTENTE]  VARCHAR (30) NOT NULL,
    CONSTRAINT [PK_SCONTRINATO_TESTATA] PRIMARY KEY CLUSTERED ([ID_SCONTRINATO] ASC)
);

