CREATE TABLE [dbo].[STATUS] (
    [STATUS_COD] VARCHAR (10)  NOT NULL,
    [STATUS_DES] VARCHAR (500) NOT NULL,
    CONSTRAINT [PK_STATUS] PRIMARY KEY CLUSTERED ([STATUS_COD] ASC)
);


GO
-- =============================================
-- Author:		Delpiano
-- Create date: 02-01-2017
-- Description:	per ogni STATUS modificato richiamo la stored 
-- che ne memorizza i dati da inviare al server centrale
-- =============================================
CREATE TRIGGER [dbo].[TRG_UPD_STATUS] 
   ON  [dbo].[STATUS]
   FOR INSERT,UPDATE
AS 
BEGIN

	SET NOCOUNT ON;

	IF EXISTS(SELECT * FROM APP_SETUP WHERE CHIAVE = 'STOP_TRIGGER_ALLINEAMENTO' AND VALORE = 'SI')
	BEGIN
		GOTO FINE
	END

	DECLARE @KEY VARCHAR(10)

	DECLARE CUR CURSOR LOCAL FOR
		SELECT STATUS_COD FROM INSERTED

	OPEN CUR

	FETCH NEXT FROM CUR INTO  @KEY

	WHILE @@FETCH_STATUS = 0 BEGIN

		EXEC PRC_AGGIORNAMENTO_DA_INVIARE_INSERT @KEY, 'STATUS'
		FETCH NEXT FROM CUR INTO @KEY
	END

	CLOSE CUR
	DEALLOCATE CUR
	FINE:

END