CREATE TABLE [dbo].[TALLONCINO_BILANCIA] (
    [NEGOZIO]        VARCHAR (10) NOT NULL,
    [EAN_TALLONCINO] VARCHAR (13) NOT NULL,
    [TRASFERITO]     CHAR (1)     CONSTRAINT [DF_TALLONCINO_BILANCIA_TRASFERITO] DEFAULT ('N') NOT NULL,
    CONSTRAINT [PK_TALLONCINO_BILANCIA] PRIMARY KEY CLUSTERED ([NEGOZIO] ASC, [EAN_TALLONCINO] ASC)
);

