CREATE TABLE [dbo].[TIPO_PAGAMENTO_old] (
    [CODICE_PAGAMENTO] VARCHAR (2)   NOT NULL,
    [DES_PAGAMENTO]    VARCHAR (50)  NOT NULL,
    [FP_TYPE]          INT           CONSTRAINT [DF_TIPO_PAGAMENTO_FP_TYPE] DEFAULT ((0)) NOT NULL,
    [FP_INDEX]         INT           CONSTRAINT [DF_TIPO_PAGAMENTO_FP_INDEX] DEFAULT ((0)) NOT NULL,
    [FP_DESCR]         NVARCHAR (50) CONSTRAINT [DF_TIPO_PAGAMENTO_FP_DESCR] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_TIPO_PAGAMENTO] PRIMARY KEY CLUSTERED ([CODICE_PAGAMENTO] ASC)
);


GO
-- =============================================
-- Author:		Delpiano
-- Create date: 02-01-2017
-- Description:	per ogni TIPO_PAGAMENTO modificato richiamo la stored 
-- che ne memorizza i dati da inviare al server centrale
-- =============================================
CREATE TRIGGER [dbo].[TRG_UPD_TIPO_PAGAMENTO] 
   ON  [dbo].[TIPO_PAGAMENTO_old]
   FOR INSERT,UPDATE
AS 
BEGIN

	SET NOCOUNT ON;

	IF EXISTS(SELECT * FROM APP_SETUP WHERE CHIAVE = 'STOP_TRIGGER_ALLINEAMENTO' AND VALORE = 'SI')
	BEGIN
		GOTO FINE
	END

	DECLARE @KEY VARCHAR(2)

	DECLARE CUR CURSOR LOCAL FOR
		SELECT CODICE_PAGAMENTO FROM INSERTED

	OPEN CUR

	FETCH NEXT FROM CUR INTO  @KEY

	WHILE @@FETCH_STATUS = 0 BEGIN

		EXEC PRC_AGGIORNAMENTO_DA_INVIARE_INSERT @KEY, 'TIPO_PAGAMENTO'
		FETCH NEXT FROM CUR INTO @KEY
	END

	CLOSE CUR
	DEALLOCATE CUR
	FINE:

END