CREATE TABLE [dbo].[UNITA_MISURA] (
    [CODICE_UM]   VARCHAR (3)  NOT NULL,
    [SIGLA]       VARCHAR (3)  NOT NULL,
    [DESCRIZIONE] VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_UNITA_MISURA] PRIMARY KEY CLUSTERED ([CODICE_UM] ASC)
);


GO
-- =============================================
-- Author:		Delpiano
-- Create date: 02-01-2017
-- Description:	per ogni UNITA_MISURA modificata richiamo la stored 
-- che ne memorizza i dati da inviare al server centrale
-- =============================================
CREATE TRIGGER [dbo].[TRG_UPD_UNITA_MISURA] 
   ON  [dbo].[UNITA_MISURA]
   FOR INSERT,UPDATE
AS 
BEGIN

	SET NOCOUNT ON;

	IF EXISTS(SELECT * FROM APP_SETUP WHERE CHIAVE = 'STOP_TRIGGER_ALLINEAMENTO' AND VALORE = 'SI')
	BEGIN
		GOTO FINE
	END
	
	DECLARE @KEY VARCHAR(3)

	DECLARE CUR CURSOR LOCAL FOR
		SELECT CODICE_UM FROM INSERTED

	OPEN CUR

	FETCH NEXT FROM CUR INTO  @KEY

	WHILE @@FETCH_STATUS = 0 BEGIN

		EXEC PRC_AGGIORNAMENTO_DA_INVIARE_INSERT @KEY, 'UNITA_MISURA'
		FETCH NEXT FROM CUR INTO @KEY
	END

	CLOSE CUR
	DEALLOCATE CUR
	
	FINE:
END