
CREATE PROCEDURE [dbo].[PRC_DELETE_INGREDIENTE]
@ID_INGREDIENTE INT,
@RISULTATO CHAR(2) = '' OUTPUT,
@DESRISULTATO VARCHAR(1000) = '' OUTPUT
AS
BEGIN
SET NOCOUNT ON
BEGIN TRY
	BEGIN TRANSACTION

	DELETE FROM INGREDIENTE WHERE ID_INGREDIENTE = @ID_INGREDIENTE
	DELETE FROM ARTICOLO_INGREDIENTE WHERE ID_INGREDIENTE = @ID_INGREDIENTE
	SET @RISULTATO = 'OK'
	SET @DESRISULTATO = 'CANCELLAZIONE EFFETTUATA'
	
	COMMIT TRANSACTION

END TRY
BEGIN CATCH
	IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
	SET @RISULTATO = 'KO'
	SET @DESRISULTATO = ERROR_MESSAGE()
END CATCH
END