-- =============================================
-- Author:		DELPIANO STEFANO
-- Create date: 23-02-2014
-- Description:	AGGIORNAMENTO GIACENZE SOTTRAENDO UN BASKET
-- =============================================
CREATE PROCEDURE [dbo].[PRC_GIACENZA_SOTTRAI_BASKET]
@ID_BASKET	INT,
@RISULTATO			CHAR(2)			= '' OUTPUT,
@DESRISULTATO		VARCHAR(1000)	= '' OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SET	@RISULTATO = 'KO'
	SET @DESRISULTATO = 'FATTO NIENTE'

BEGIN TRY
	
	BEGIN TRANSACTION 	
	SELECT B.EAN  AS BARCODE, SUM(QTA) AS QTA  
	INTO #BASKETGIAC
	FROM 
	BASKET_RIGA B WITH (NOLOCK) 
	WHERE
	ID_BASKET = @ID_BASKET
	GROUP BY
	B.EAN	
		
	UPDATE GIACENZA
			SET GIACENZA = GIACENZA - QTA
	FROM #BASKETGIAC 	
			JOIN GIACENZA G  ON BARCODE = EAN
	SET @RISULTATO = 'OK'
	SET @DESRISULTATO = 'COMANDA CREATA CORRETTAMENTE'


END TRY
BEGIN CATCH
    PRINT 'VADO IN ERRORE'
    SET @RISULTATO = 'KO ' + ERROR_MESSAGE()
    SET @DESRISULTATO = ERROR_MESSAGE()
    
	CLOSE CURREPARTI
	DEALLOCATE CURREPARTI
END CATCH	

	FINE:
	PRINT @RISULTATO
	PRINT @DESRISULTATO
	
	IF SUBSTRING(@RISULTATO, 1 , 2) = 'OK' 
		COMMIT TRANSACTION
	ELSE
		ROLLBACK TRANSACTION
		


END