create PROCEDURE [dbo].[PRC_DELETE_BASKET_RIGA]
@ID_BASKET			  INT,
@RISULTATO			  CHAR(2) = '' OUTPUT,
@DESRISULTATO		  VARCHAR(1000)	= '' OUTPUT
AS
SET NOCOUNT ON
BEGIN TRY
	BEGIN TRANSACTION
	DELETE FROM BASKET_RIGA WHERE ID_BASKET = @ID_BASKET
	SET @RISULTATO = 'OK'
	SET @DESRISULTATO = 'CANCELLAZIONE EFFETTUATA'
	COMMIT TRANSACTION
END TRY
BEGIN CATCH
	ROLLBACK TRANSACTION
	SET @RISULTATO = 'KO'
	SET @DESRISULTATO = ERROR_MESSAGE()
END CATCH