
CREATE PROCEDURE [dbo].[PRC_GET_BASKET_APERTO]
@TAVOLO INT
AS
SET NOCOUNT ON

select * from [dbo].[BASKET_TESTATA] t
   join [dbo].[BASKET_RIGA] r on t.ID_BASKET = r.ID_BASKET
  where TAVOLO = @TAVOLO
   and  EVASO = 0