-- =============================================
-- Author:		DELPIANO STEFANO
-- Create date: 16-05-2015
-- Description:	IMPORT SCONTRINO DA DOCUMENTO XML
-- =============================================
CREATE PROCEDURE [dbo].[PRC_IMPORT_SCO]
@DOCXML				NVARCHAR(MAX),
@RISULTATO			CHAR(2)			= '' OUTPUT,			
@DESRISULTATO		VARCHAR(1000)	= '' OUTPUT	
AS
BEGIN

	SET NOCOUNT ON;

	BEGIN TRY
	
	BEGIN TRANSACTION 

		DECLARE @HDOC 		INT


		EXEC 		SP_XML_PREPAREDOCUMENT @HDOC OUTPUT,@DOCXML

		-- TESTATA --
		SELECT * 
		INTO #TESTATA
		FROM OPENXML(@HDOC, 'SCONTRINO/TESTATA',2)
		WITH
		(
		CODICE_NEGOZIO    VARCHAR(10),
		DATA              VARCHAR(08),
		ORA               VARCHAR(06),
		CASSA             INT,
		SCONTRINO         INT,
		ID_PROVENIENZA    VARCHAR(3),
		ID_BASKET         INT,
		STAMPATO          CHAR(1),
		PAGATO            CHAR(1),
		INVIATO           CHAR(1),
		TOTALE            MONEY,
		CODICE_UTENTE     varchar(30)
		)


		---- RIGHE --
		SELECT  * 
		INTO #RIGHE
		FROM OPENXML(@HDOC, 'SCONTRINO/RIGHE',2)
		WITH
		(
		CODICE_NEGOZIO    VARCHAR(10),
		DATA              VARCHAR(08),
		ORA               VARCHAR(06),
		CASSA             INT,
		SCONTRINO         INT,		
		RIGA			  INT,
		EAN				  VARCHAR(13),
		PREZZO			  MONEY,
		QTA               DECIMAL(8, 3),
		REPARTO_VENDITA	  VARCHAR(1),
		LOTTO_VENDITA	  VARCHAR(1)
		)
		
		---- PAGAMENTO --
		SELECT  * 
		INTO #PAGAMENTO
		FROM OPENXML(@HDOC, 'SCONTRINO/PAGAMENTO',2)
		WITH
		(
		CODICE_NEGOZIO    VARCHAR(10),
		DATA              VARCHAR(08),
		ORA               VARCHAR(06),
		CASSA             INT,
		SCONTRINO         INT,		
		TIPO_PAGAMENTO    VARCHAR(10),
		IMPORTO			  MONEY
		)
		

		EXEC SP_XML_REMOVEDOCUMENT @HDOC


		DELETE  SCONTRINATO_TESTATA
		FROM SCONTRINATO_TESTATA A JOIN  #TESTATA B ON 
			A.CODICE_NEGOZIO    = B.CODICE_NEGOZIO		AND
			A.DATA              = B.DATA				AND
			A.ORA               = B.ORA					AND
			A.CASSA             = B.CASSA				AND
			A.SCONTRINO         = B.SCONTRINO	

		DELETE  SCONTRINATO_RIGA
		FROM SCONTRINATO_RIGA A JOIN  #TESTATA B ON 
			A.CODICE_NEGOZIO    = B.CODICE_NEGOZIO		AND
			A.DATA              = B.DATA				AND
			A.ORA               = B.ORA					AND
			A.CASSA             = B.CASSA				AND
			A.SCONTRINO         = B.SCONTRINO	
			
		DELETE  SCONTRINATO_PAGAMENTO
		FROM SCONTRINATO_PAGAMENTO A JOIN  #TESTATA B ON 
			A.CODICE_NEGOZIO    = B.CODICE_NEGOZIO		AND
			A.DATA              = B.DATA				AND
			A.ORA               = B.ORA					AND
			A.CASSA             = B.CASSA				AND
			A.SCONTRINO         = B.SCONTRINO			
		

		INSERT INTO
			SCONTRINATO_TESTATA
			(
			CODICE_NEGOZIO,
			DATA,
			ORA,
			CASSA,
			SCONTRINO,
			ID_PROVENIENZA,
			ID_BASKET,
			STAMPATO,
			PAGATO,
			INVIATO,
			TOTALE,
			CODICE_UTENTE
			)
		SELECT
			CODICE_NEGOZIO,
			DATA,
			ORA,
			CASSA,
			SCONTRINO,
			ID_PROVENIENZA,
			ID_BASKET,
			STAMPATO,
			PAGATO,
			'S',
			TOTALE,
			CODICE_UTENTE
			FROM #TESTATA		

		INSERT INTO
			SCONTRINATO_RIGA											
			(
			CODICE_NEGOZIO,
			DATA,
			ORA,
			CASSA,
			SCONTRINO,	
			RIGA,
			EAN,
			PREZZO,
			QTA,
			REPARTO_VENDITA,
			LOTTO_VENDITA
			)
			SELECT
			CODICE_NEGOZIO,
			DATA,
			ORA,
			CASSA,
			SCONTRINO,	
			RIGA,
			EAN,
			PREZZO,
			QTA,
			REPARTO_VENDITA,
			LOTTO_VENDITA			
			FROM #RIGHE


		INSERT INTO
			SCONTRINATO_PAGAMENTO											
			(
			CODICE_NEGOZIO,
			DATA,
			ORA,
			CASSA,
			SCONTRINO,	
			TIPO_PAGAMENTO,
			IMPORTO
			)
			SELECT
			CODICE_NEGOZIO,
			DATA,
			ORA,
			CASSA,
			SCONTRINO,	
			TIPO_PAGAMENTO,
			IMPORTO
			FROM #PAGAMENTO



	SET @RISULTATO = 'OK'
	SET @DESRISULTATO = ''


END TRY
BEGIN CATCH
    SET @RISULTATO = 'KO ' + ERROR_MESSAGE()
    SET @DESRISULTATO = ERROR_MESSAGE()
END CATCH	

	FINE:
	PRINT @RISULTATO
	PRINT @DESRISULTATO
	
	IF SUBSTRING(@RISULTATO, 1 , 2) = 'OK' 
		COMMIT TRANSACTION
	ELSE
		ROLLBACK TRANSACTION
		






END