-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[PRC_DELETE_SOTTOCANALE]
@ID_SOTTOCANALE INT  , 
@RISULTATO		     CHAR(2)			= '' OUTPUT,
@DESRISULTATO	     VARCHAR(1000)	= '' OUTPUT
AS
BEGIN

	SET NOCOUNT ON;

BEGIN TRY
	
	BEGIN TRANSACTION 		
	
	IF EXISTS (SELECT * FROM SOTTOCANALE WHERE  @ID_SOTTOCANALE=@ID_SOTTOCANALE)
	BEGIN
		DELETE FROM  SOTTOCANALE WHERE ID_SOTTOCANALE=@ID_SOTTOCANALE 	  
		SET @RISULTATO = 'OK'
		SET @DESRISULTATO = 'CANCELLAZIONE ESEGUITA CORRETTAMENTE'
	END

END TRY
BEGIN CATCH
    SET @RISULTATO = 'KO ' + ERROR_MESSAGE()
    SET @DESRISULTATO = ERROR_MESSAGE()
END CATCH	

	FINE:

	IF SUBSTRING(@RISULTATO, 1 , 2) = 'OK' 
		COMMIT TRANSACTION
	ELSE
		ROLLBACK TRANSACTION
		
END