
CREATE PROCEDURE [dbo].[PRC_GET_ARTICOLO_INGREDIENTI]
@ID_ARTICOLO INT
AS
BEGIN
	SET NOCOUNT ON
	SELECT I.* FROM INGREDIENTE I 
	JOIN ARTICOLO_INGREDIENTE AI ON AI.ID_INGREDIENTE = I.ID_INGREDIENTE WHERE ID_ARTICOLO = @ID_ARTICOLO
	order by [DESCRIZIONE]
END