CREATE PROCEDURE [dbo].[PRC_GET_RigheScontrini_Dett]
 @CODICE_NEGOZIO	VARCHAR(10),
 @DATA	INT,
 @PRODOTTO VARCHAR(13) = NULL,
 @REPARTO_VENDITA VARCHAR(10) = NULL,
 @CANALE_VENDITA VARCHAR(10) = NULL	
AS

   
SELECT  T.DATA,SUBSTRING(T.ORA, 1,2) + ':' + SUBSTRING(T.ORA, 3,2) AS ORA ,
		 CONVERT(VARCHAR(50),T.SCONTRINO) AS SCONTRINO_CHAR, T.SCONTRINO , P.IMPORTO AS TOTALE, --T.TOTALE,
		 TP.DES_PAGAMENTO, P.TIPO_PAGAMENTO, T.CASSA, t.ORA as ORAHHMMSS
FROM DBO.SCONTRINATO_TESTATA AS T
LEFT JOIN (
	SELECT R.DATA,R.ORA,R.CASSA,R.CODICE_NEGOZIO , R.scontrino
	FROM DBO.SCONTRINATO_RIGA AS R
	WHERE  R.EAN = isnull(@PRODOTTO ,EAN)
			AND R.REPARTO_VENDITA = isnull(@REPARTO_VENDITA , REPARTO_VENDITA)
			AND R.LOTTO_VENDITA = isnull(@CANALE_VENDITA , LOTTO_VENDITA)
	GROUP BY R.CASSA, R.DATA,R.ORA,R.CODICE_NEGOZIO,R.SCONTRINO
	)A ON ( 
		A.DATA = T.DATA AND A.ORA = T.ORA
		AND A.CASSA = T.CASSA  AND A.CODICE_NEGOZIO = T.CODICE_NEGOZIO and A.scontrino = T.scontrino 
	)
 JOIN DBO.SCONTRINATO_PAGAMENTO AS P
	ON (T.CODICE_NEGOZIO = P.CODICE_NEGOZIO AND T.DATA = P.DATA 
		AND T.ORA = P.ORA AND T.CASSA = P.CASSA AND T.SCONTRINO = P.SCONTRINO )
LEFT JOIN DBO.TIPO_PAGAMENTO TP ON P.TIPO_PAGAMENTO = TP.CODICE_PAGAMENTO
WHERE T.DATA = @DATA 
AND T.CODICE_NEGOZIO = @CODICE_NEGOZIO
ORDER BY T.DATA,T.SCONTRINO