CREATE PROCEDURE [dbo].[PRC_DELETE_USER_NEGOZIO]
@USER_ID     INT,
@RISULTATO			CHAR(2)			= '' OUTPUT,
@DESRISULTATO		VARCHAR(1000)	= '' OUTPUT
AS
BEGIN

	SET NOCOUNT ON;

BEGIN TRY
	
	BEGIN TRANSACTION 		
	
	IF EXISTS (SELECT * FROM USER_NEGOZIO WHERE UserId=@USER_ID)
	BEGIN
		DELETE FROM  USER_NEGOZIO WHERE UserId=@USER_ID	  
		SET @RISULTATO = 'OK'
		SET @DESRISULTATO = 'CANCELLAZIONE ESEGUITA CORRETTAMENTE'
	END

END TRY
BEGIN CATCH
    SET @RISULTATO = 'KO ' + ERROR_MESSAGE()
    SET @DESRISULTATO = ERROR_MESSAGE()
END CATCH	

	FINE:

	IF SUBSTRING(@RISULTATO, 1 , 2) = 'OK' 
		COMMIT TRANSACTION
	ELSE
		ROLLBACK TRANSACTION
		
END