

CREATE PROCEDURE [dbo].[PRC_INSERT_UPD_CATEGORIA]
@ID_CATEGORIA	 	  INT,
@ORDINE			 	  INT,
@DESCRIZIONE 	      VARCHAR(200),
@IMMAGINE	 	      VARCHAR(400),
@STATUS		 	      VARCHAR(10),
@VISUALIZZA		 	  VARCHAR(10),
@DESCRIZIONE_INGLESE  VARCHAR(200),
@DESCRIZIONE_FRANCESE VARCHAR(200),
@RISULTATO			  CHAR(2)		= '' OUTPUT,
@DESRISULTATO		  VARCHAR(1000)	= '' OUTPUT
AS
	SET NOCOUNT ON

	DECLARE @CATEGORIA TABLE (ID_CATEGORIA INT)

	BEGIN TRY
	
		BEGIN TRANSACTION 
		
		IF @ORDINE = 0 OR @ORDINE = NULL 
		BEGIN
			SELECT @ORDINE = MAX(ORDINE)+1 FROM CATEGORIA
		END 
		
		MERGE CATEGORIA AS target
			USING (SELECT @ID_CATEGORIA, @DESCRIZIONE, @IMMAGINE, @STATUS, @ORDINE, @VISUALIZZA ) 
				AS source (ID_CATEGORIA, DESCRIZIONE, IMMAGINE, STATUS, ORDINE, VISUALIZZA)  
			ON (target.ID_CATEGORIA = source.ID_CATEGORIA)  
			WHEN MATCHED THEN
				UPDATE SET DESCRIZIONE_CATEGORIA  = source.DESCRIZIONE,  
						   IMMAGINE  = source.IMMAGINE,  
						   STATUS  = source.STATUS,  
						   ORDINE  = source.ORDINE,  
						   VISUALIZZA  = source.VISUALIZZA  
			WHEN NOT MATCHED THEN  
				INSERT ( DESCRIZIONE_CATEGORIA, IMMAGINE, STATUS, ORDINE, VISUALIZZA) 
				VALUES (source.DESCRIZIONE,source.IMMAGINE, source.STATUS, source.ORDINE, source.VISUALIZZA)
			OUTPUT inserted.ID_CATEGORIA INTO @CATEGORIA;  

		SELECT @ID_CATEGORIA = ID_CATEGORIA FROM @CATEGORIA

		MERGE CATEGORIA_LINGUA AS target
			USING (SELECT @ID_CATEGORIA, 2, @DESCRIZIONE_INGLESE, @IMMAGINE, @STATUS)
				AS source (ID_CATEGORIA, ID_LINGUA, DESCRIZIONE_CATEGORIA, IMMAGINE, STATUS)
			ON (target.ID_CATEGORIA = source.ID_CATEGORIA and target.ID_LINGUA = 2)
			WHEN MATCHED THEN
				UPDATE SET DESCRIZIONE_CATEGORIA  = SOURCE.DESCRIZIONE_CATEGORIA,
						   ID_LINGUA  = SOURCE.ID_LINGUA,
						   IMMAGINE  = SOURCE.IMMAGINE,
						   STATUS = SOURCE.STATUS
			WHEN NOT MATCHED THEN
				INSERT (ID_CATEGORIA,  DESCRIZIONE_CATEGORIA, ID_LINGUA, IMMAGINE, STATUS)
				VALUES (@ID_CATEGORIA, SOURCE.DESCRIZIONE_CATEGORIA, SOURCE.ID_LINGUA, SOURCE.IMMAGINE, SOURCE.STATUS);

		MERGE CATEGORIA_LINGUA AS target
			USING (SELECT @ID_CATEGORIA, 3, @DESCRIZIONE_FRANCESE, @IMMAGINE, @STATUS)
				AS source (ID_CATEGORIA, ID_LINGUA, DESCRIZIONE_CATEGORIA, IMMAGINE, STATUS)
			ON (target.ID_CATEGORIA = SOURCE.ID_CATEGORIA and target.ID_LINGUA = 3)
			WHEN MATCHED THEN
				UPDATE SET DESCRIZIONE_CATEGORIA  = SOURCE.DESCRIZIONE_CATEGORIA,
						   ID_LINGUA  = SOURCE.ID_LINGUA,
						   IMMAGINE  = SOURCE.IMMAGINE,
						   STATUS = SOURCE.STATUS
			WHEN NOT MATCHED THEN
				INSERT (ID_CATEGORIA,  DESCRIZIONE_CATEGORIA, ID_LINGUA, IMMAGINE, STATUS)
				VALUES (@ID_CATEGORIA, SOURCE.DESCRIZIONE_CATEGORIA, SOURCE.ID_LINGUA, SOURCE.IMMAGINE, SOURCE.STATUS);

		SET @RISULTATO = 'OK'
		SET @DESRISULTATO = 'INSERIMENTO/AGGIORNAMENTO EFFETTUATO'
		
	END TRY
	BEGIN CATCH
		SET @RISULTATO = 'KO'
		SET @DESRISULTATO = ERROR_MESSAGE()
	END CATCH

	IF @RISULTATO = 'OK'
		COMMIT TRANSACTION
	ELSE
		ROLLBACK TRANSACTION