CREATE PROCEDURE [dbo].[PRC_GET_PROGRESSIVO]
@CHIAVE 	VARCHAR(15),
@CODICE_NEGOZIO 	VARCHAR(10),
@PROG	 INT =0 	OUTPUT
AS
	SET NOCOUNT ON
	IF EXISTS(SELECT PROGR FROM PROGRESSIVO WHERE CODICE = @CHIAVE and CODICE_NEGOZIO = @CODICE_NEGOZIO )
	BEGIN
		UPDATE    	PROGRESSIVO
		SET       	PROGR =(SELECT ISNULL(MAX(PROGR), 0) + 1
				FROM 		PROGRESSIVO
				WHERE 	CODICE = @CHIAVE and CODICE_NEGOZIO = @CODICE_NEGOZIO)
		WHERE     CODICE = @CHIAVE
	END
	ELSE
	BEGIN
		--PRINT ' NON ESISTE PROGRESSIVO LO INSERISCO'
		INSERT PROGRESSIVO(CODICE_NEGOZIO,CODICE, PROGR) VALUES(@CODICE_NEGOZIO,@CHIAVE, 1)
	END
		
	SELECT @PROG = PROGR FROM PROGRESSIVO  WHERE CODICE = @CHIAVE and CODICE_NEGOZIO = @CODICE_NEGOZIO
	--PRINT 'TROVATO ' + CONVERT(VARCHAR,@PROG)
	RETURN (@PROG)