CREATE PROCEDURE [dbo].[PRC_GET_BASKET_BOX]
@ID_BASKET INT
AS
SET NOCOUNT ON
SELECT r.ID_BASKET, r.ID_MENU, r.ID_ARTICOLO, r.QTA - r.QTA_INVIATA AS QTA, r.PREZZO, r.ISTRUZIONI,
ORDINE, c.ID_CATEGORIA, c.DESCRIZIONE_CATEGORIA, a.NOME,
DENSE_RANK() OVER (ORDER BY ORDINE) as BOX
FROM BASKET_RIGA r
join ARTICOLO a on r.ID_ARTICOLO = a.ID_ARTICOLO
join CATEGORIA c on a.ID_CATEGORIA = c.ID_CATEGORIA
where r.ID_BASKET = @ID_BASKET AND A.ID_REPARTO = 1 AND c.ID_CATEGORIA <> 100
AND r.QTA <> r.QTA_INVIATA
order by ORDINE