CREATE PROCEDURE [dbo].[PRC_GET_COMANDA_TESTATA]
@ID_COMANDA INT = 0,
@ID_BASKET INT = 0,
@ROWS INT = 0
AS
	SET NOCOUNT ON
	IF @ROWS = 0
		SELECT * FROM COMANDA_TESTATA WHERE ID_COMANDA = @ID_COMANDA
	ELSE
		SELECT TOP (@ROWS) * FROM COMANDA_TESTATA WHERE ID_BASKET = @ID_BASKET ORDER BY ID_COMANDA DESC