-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[PRC_INSERT_UPD_CANALE_DI_VENDITA]
@NEGOZIO			    VARCHAR(10)		= '', 
@COD_CANALE_VENDITA		VARCHAR(10)	    = '0',
@DES_CANALE_VENDITA	    VARCHAR(500)     = '', 
@SIGLA_CANALE_VENDITA	VARCHAR(25)		= '', 

@RISULTATO			    CHAR(2)			= '' OUTPUT,
@DESRISULTATO	    	VARCHAR(1000)	= '' OUTPUT
AS
BEGIN

	SET NOCOUNT ON;

BEGIN TRY
	
	BEGIN TRANSACTION 
	


		IF EXISTS(SELECT COD_CANALE_VENDITA FROM CANALE_VENDITA  WHERE  COD_NEGOZIO=@NEGOZIO  AND  COD_CANALE_VENDITA =@COD_CANALE_VENDITA  )		
			BEGIN
				UPDATE CANALE_VENDITA
					SET 
                  	COD_NEGOZIO= @NEGOZIO,
				    COD_CANALE_VENDITA   = @COD_CANALE_VENDITA,	
					DES_CANALE_VENDITA	 = @DES_CANALE_VENDITA,
					SIGLA_CANALE_VENDITA = @SIGLA_CANALE_VENDITA
				WHERE COD_CANALE_VENDITA = @COD_CANALE_VENDITA 
				
				SET @RISULTATO		= 'OK' 
				SET @DESRISULTATO	= 'TUTTO OK'	
			END
		ELSE
		BEGIN
				IF NOT EXISTS(SELECT COD_CANALE_VENDITA FROM CANALE_VENDITA WHERE COD_CANALE_VENDITA = @COD_CANALE_VENDITA)
				BEGIN
				
					INSERT INTO CANALE_VENDITA
						(COD_NEGOZIO, COD_CANALE_VENDITA,  DES_CANALE_VENDITA, SIGLA_CANALE_VENDITA )
					VALUES
						(@NEGOZIO, @COD_CANALE_VENDITA , @DES_CANALE_VENDITA, @SIGLA_CANALE_VENDITA)
							
					SET @RISULTATO		= 'OK' 
					SET @DESRISULTATO	= 'TUTTO OK'
				END	
				ELSE
				BEGIN
				    SET @RISULTATO		= 'KO' 
					SET @DESRISULTATO	= 'CODICE CANALE VENDITA  PREESISTENTE'	
				END
		END	

END TRY
BEGIN CATCH
    SET @RISULTATO = 'KO'
	SET @DESRISULTATO = ERROR_MESSAGE()
END CATCH
		
IF @RISULTATO = 'OK' 
	COMMIT TRANSACTION
ELSE
	ROLLBACK TRANSACTION
END