-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[PRC_GET_CANALE_VENDITA_byCOD_CANALE_VENDITA] 
	@CODICE_NEGOZIO VARCHAR(10)= '001',
	@COD_CANALE_VENDITA   VARCHAR(10)= ' ' ,
	@DES_CANALE_VENDITA VARCHAR(500)= ' ' ,
	@SIGLA_CANALE_VENDITA VARCHAR(250)= ' '
	
AS
BEGIN

	SET NOCOUNT ON

    SELECT  COD_NEGOZIO , COD_CANALE_VENDITA, DES_CANALE_VENDITA, SIGLA_CANALE_VENDITA 
    FROM CANALE_VENDITA 
	WHERE
	COD_NEGOZIO = @CODICE_NEGOZIO  AND
	CANALE_VENDITA.COD_CANALE_VENDITA = CASE WHEN @COD_CANALE_VENDITA = '0' THEN CANALE_VENDITA.COD_CANALE_VENDITA ELSE @COD_CANALE_VENDITA END 
	--COD_CANALE_VENDITA =  @COD_CANALE_VENDITA   
END