


CREATE PROCEDURE [dbo].[PRC_GET_ARTICOLObyCODICE_ARTICOLO]
 @COD_ARTICOLO		VARCHAR(20),
 @CODICE_NEGOZIO	VARCHAR(10) = ''
 	
AS

	/*DECLARE @COD_ARTICOLO_like VARCHAR(20)
	set @COD_ARTICOLO_like = @COD_ARTICOLO + '%'*/
	SET NOCOUNT ON
	
	SELECT ARTICOLO.*, ISNULL(CAST(giacenza AS INT),0) as giacenza,
	ISNULL(DESCRIZIONE_CATEGORIA,'') as des_categoria
	FROM ARTICOLO
	left join GIACENZA ON GIACENZA.ID_ARTICOLO = ARTICOLO.ID_ARTICOLO 
	left join CATEGORIA ON CATEGORIA.ID_CATEGORIA = ARTICOLO.ID_CATEGORIA
	WHERE CODICE_NEGOZIO = CASE WHEN @CODICE_NEGOZIO = '' THEN CODICE_NEGOZIO ELSE @CODICE_NEGOZIO END
	AND	CODICE_ARTICOLO = @COD_ARTICOLO AND ARTICOLO.STATUS = 'V'