CREATE PROCEDURE [dbo].[PRC_GET_VendutoByPar]
 @CODICE_NEGOZIO VARCHAR(10),
 @DATEFROM INT,
 @DATETO INT,
 @PRODOTTO VARCHAR(13) = NULL,
 @REPARTO_VENDITA VARCHAR(10) = NULL,
 @CANALE_VENDITA VARCHAR(10) = NULL,
 @GROUP INT --criterio di raggruppamento
			-- 1 = per mese
 			-- 2 = per prodotto
 			-- 3 = per pagamento
 			-- 4 = per giorno
AS

if @PRODOTTO = ''
	set @PRODOTTO = null
if @REPARTO_VENDITA = ''
	set @REPARTO_VENDITA = null
if @CANALE_VENDITA = ''
	set @CANALE_VENDITA = null

if @GROUP = 1
begin
	--X MESE
	SELECT SUBSTRING(DATA,5,2) + '/' + SUBSTRING(DATA,1,4) as RAGGR,SUM(PREZZO) as IMPORTO
	FROM dbo.SCONTRINATO_RIGA
	WHERE DATA >= @DATEFROM and DATA <= @DATETO
		AND CODICE_NEGOZIO = @CODICE_NEGOZIO
		AND EAN = isnull(@PRODOTTO ,EAN)
		AND REPARTO_VENDITA = isnull(@REPARTO_VENDITA , REPARTO_VENDITA)
		AND LOTTO_VENDITA = isnull(@CANALE_VENDITA , LOTTO_VENDITA)
	GROUP BY SUBSTRING(DATA,5,2), SUBSTRING(DATA,1,4)
	ORDER BY SUBSTRING(DATA,5,2), SUBSTRING(DATA,1,4)
end

if @GROUP = 2
begin
	--X PRODOTTO
	SELECT CODICE_ARTICOLO, NOME+' '+NOME_BREVE  as RAGGR, SUM(QTA) as QTA, CODICE_UM, SUM(PREZZO) as IMPORTO, COUNT(*) as NUMERO_SCONTRINI, 
		   CV.DES_CANALE_VENDITA, RV.DES_REPARTO_VENDITA
	FROM dbo.SCONTRINATO_RIGA as SR
	JOIN ARTICOLO ON EAN = ID_ARTICOLO
	JOIN CANALE_VENDITA AS CV ON COD_CANALE_VENDITA = SR.LOTTO_VENDITA 
	JOIN REPARTO_VENDITA AS RV ON COD_REPARTO_VENDITA = SR.REPARTO_VENDITA  
	WHERE DATA >= @DATEFROM AND DATA <= @DATETO
		AND CODICE_NEGOZIO = @CODICE_NEGOZIO
		AND EAN = isnull(@PRODOTTO ,EAN) 
		AND SR.REPARTO_VENDITA = isnull(@REPARTO_VENDITA , SR.REPARTO_VENDITA)
		AND SR.LOTTO_VENDITA = isnull(@CANALE_VENDITA , SR.LOTTO_VENDITA)
	GROUP BY CODICE_ARTICOLO, NOME, NOME_BREVE, CODICE_UM, CV.DES_CANALE_VENDITA, RV.DES_REPARTO_VENDITA
	ORDER BY CV.DES_CANALE_VENDITA, RV.DES_REPARTO_VENDITA, NOME,NOME_BREVE
	--order by numero_scontrini desc
end




if @GROUP = 3
begin
--X PAGAMENTO
	SELECT DES_PAGAMENTO as RAGGR,SUM(PREZZO) as IMPORTO
	FROM dbo.SCONTRINATO_RIGA R
	JOIN DBO.SCONTRINATO_TESTATA T ON 
		T.CODICE_NEGOZIO = R.CODICE_NEGOZIO
		AND T.DATA = R.DATA
		AND T.ORA = R.ORA
		AND T.CASSA = R.CASSA
		AND T.SCONTRINO = R.SCONTRINO
	LEFT JOIN DBO.SCONTRINATO_PAGAMENTO AS P ON 
		T.CODICE_NEGOZIO = P.CODICE_NEGOZIO AND T.DATA = P.DATA 
		AND T.ORA = P.ORA AND T.CASSA = P.CASSA AND T.SCONTRINO = P.SCONTRINO 
	LEFT JOIN DBO.TIPO_PAGAMENTO ON P.TIPO_PAGAMENTO = CODICE_PAGAMENTO 
	WHERE T.DATA >= @DATEFROM and T.DATA <= @DATETO
		AND T.CODICE_NEGOZIO = @CODICE_NEGOZIO
		AND EAN = isnull(@PRODOTTO ,EAN)
		AND R.REPARTO_VENDITA = isnull(@REPARTO_VENDITA , R.REPARTO_VENDITA)
		AND R.LOTTO_VENDITA = isnull(@CANALE_VENDITA , R.LOTTO_VENDITA)
 	GROUP BY DES_PAGAMENTO
	ORDER BY DES_PAGAMENTO
	
end

if @GROUP = 4
begin
	--X GIORNO
	SELECT SUBSTRING(DATA,7,2) + '/' + SUBSTRING(DATA,5,2) + '/' + SUBSTRING(DATA,1,4) as RAGGR,SUM(PREZZO) as IMPORTO
	FROM dbo.SCONTRINATO_RIGA
	WHERE DATA >= @DATEFROM and DATA <= @DATETO
		AND CODICE_NEGOZIO = @CODICE_NEGOZIO
		AND EAN = isnull(@PRODOTTO ,EAN) 
		AND REPARTO_VENDITA = isnull(@REPARTO_VENDITA , REPARTO_VENDITA)
		AND LOTTO_VENDITA = isnull(@CANALE_VENDITA , LOTTO_VENDITA)
	GROUP BY DATA
	ORDER BY DATA
end