

CREATE PROCEDURE [dbo].[PRC_GET_ARTICOLO_ALLERGENI]
@ID_ARTICOLO INT
AS
BEGIN
	SET NOCOUNT ON
	SELECT A.* FROM ALLERGENE A JOIN ARTICOLO_ALLERGENE AA ON AA.ID_ALLERGENE = A.ID_ALLERGENE
	WHERE ID_ARTICOLO = @ID_ARTICOLO
	ORDER BY DESCRIZIONE
END