CREATE PROCEDURE [dbo].[PRC_GET_EAN_BY_ID_ARTICOLO]
 @ID_ARTICOLO INT=0
AS
	SET NOCOUNT ON
	
	SELECT A.ID_ARTICOLO ,B.GIACENZA ,A.NOME_BREVE ,A.PREZZO_BASE
	FROM ARTICOLO A , GIACENZA B 
	WHERE
	A.ID_ARTICOLO = @ID_ARTICOLO AND 
	A.ID_ARTICOLO = B.EAN