CREATE PROCEDURE [dbo].[PRC_GET_CATEGORIA_LINGUA]
 @ID_CATEGORIA	INT=0,
 @ID_LINGUA		INT=0,
 @SORT			CHAR(1) = 'O' -- A = alfabetico / O = ordine (campo della tabella)
AS
	SET NOCOUNT ON
	
	SELECT	CATEGORIA.ID_CATEGORIA, CATEGORIA.DESCRIZIONE_CATEGORIA, ORDINE  ,en.DESCRIZIONE_CATEGORIA as DESCRIZIONE_CATEGORIA_EN, fr.DESCRIZIONE_CATEGORIA as DESCRIZIONE_CATEGORIA_FR
	INTO	#RISULTATO
	FROM	CATEGORIA 
	left join 
	(select * from CATEGORIA_LINGUA where ID_LINGUA=2 ) as EN
	on CATEGORIA.ID_CATEGORIA= EN.ID_CATEGORIA
	left join 
	(select * from CATEGORIA_LINGUA where ID_LINGUA=3) as FR
	on CATEGORIA.ID_CATEGORIA= FR.ID_CATEGORIA
	 
	WHERE
	CATEGORIA.ID_CATEGORIA =	CASE WHEN @ID_CATEGORIA = 0 THEN CATEGORIA.ID_CATEGORIA ELSE @ID_CATEGORIA END 

	
	IF @ID_LINGUA <> 0
	BEGIN

			UPDATE #RISULTATO 
					SET #RISULTATO.DESCRIZIONE_CATEGORIA = CATEGORIA_LINGUA.DESCRIZIONE_CATEGORIA
			FROM
					#RISULTATO  JOIN CATEGORIA_LINGUA  
					ON #RISULTATO.ID_CATEGORIA = CATEGORIA_LINGUA.ID_CATEGORIA AND ID_LINGUA = @ID_LINGUA				
	END

	IF @SORT = 'A'
		SELECT * FROM #RISULTATO	ORDER BY DESCRIZIONE_CATEGORIA	
	ELSE
		SELECT * FROM #RISULTATO	ORDER BY ORDINE, DESCRIZIONE_CATEGORIA