

-- ======================================================================
-- Author:		FRANCESCO TATARANNI
-- Create date: 01-09-2020
-- Description:	CANCELLAZIONE DI UN MENU E DEI RELATIVI ARTICOLI
-- ======================================================================
CREATE PROCEDURE [dbo].[PRC_DELETE_MENU]
@ID_MENU INT,
@RISULTATO CHAR(2) = '' OUTPUT,
@DESRISULTATO VARCHAR(1000) = '' OUTPUT
AS
BEGIN
SET NOCOUNT ON
BEGIN TRY
	BEGIN TRANSACTION
	DELETE FROM MENU_ARTICOLO WHERE ID_MENU = @ID_MENU
	UPDATE MENU SET STATUS = 'C' WHERE ID_MENU = @ID_MENU
	SET @RISULTATO = 'OK'
	SET @DESRISULTATO = 'CANCELLAZIONE EFFETTUATA'
	COMMIT TRANSACTION
END TRY
BEGIN CATCH
	IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
	SET @RISULTATO = 'KO'
	SET @DESRISULTATO = ERROR_MESSAGE()
END CATCH
END