

CREATE PROCEDURE [dbo].[PRC_GET_ARTICOLI]
@ID_ARTICOLO INT = 0,
@ID_CATEGORIA INT = 0,
@ID_LINGUA INT = 0,
@VISIBILI BIT = 0
AS
	SET NOCOUNT ON
	
	SELECT A.ID_ARTICOLO, CASE WHEN @ID_LINGUA = 0 THEN NOME ELSE AL.DESCRIZIONE END NOME,
	A.DESCRIZIONE, A.ID_CATEGORIA, DEFAULT_IMAGE, PREZZO, ID_REPARTO, A.STATUS,
	ISNULL(DESCRIZIONE_CATEGORIA, '') DES_CATEGORIA, CASE WHEN C.ORDINE IS NULL THEN 0 ELSE C.ORDINE END ORDINE, C.IMMAGINE, C.STATUS STATUS_CATEGORIA, C.VISUALIZZA,
	ISNULL(DESCRIZIONEREPARTO, '') DES_REPARTO, R.CODICE_NEGOZIO, R.DESCRIZIONECORTA, R.NOMESTAMPANTECOMANDA, R.STATUS REP_STATUS, R.VISUALIZZA,
	DECONGELATO
	FROM ARTICOLO A
	JOIN CATEGORIA C ON C.ID_CATEGORIA = A.ID_CATEGORIA
	JOIN REPARTO R ON R.IDREPARTO = A.ID_REPARTO
	LEFT JOIN (SELECT * FROM ARTICOLO_LINGUA WHERE ID_LINGUA = @ID_LINGUA) AL ON AL.ID_ARTICOLO = A.ID_ARTICOLO
	WHERE A.STATUS = 'V' 
	AND A.ID_ARTICOLO = CASE WHEN @ID_ARTICOLO = 0 THEN A.ID_ARTICOLO ELSE @ID_ARTICOLO END
	AND A.ID_ARTICOLO = CASE WHEN @ID_ARTICOLO = 0 THEN A.ID_ARTICOLO ELSE @ID_ARTICOLO END
	AND A.ID_CATEGORIA = CASE WHEN @ID_CATEGORIA = 0 THEN A.ID_CATEGORIA ELSE @ID_CATEGORIA END	
	AND C.VISUALIZZA = CASE WHEN @VISIBILI = 0 THEN C.VISUALIZZA ELSE @VISIBILI END