
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[PRC_DELETE_TIPO_PAGAMENTO]
@ID_PAGAMENTO		int,
@RISULTATO			CHAR(2)			= '' OUTPUT,
@DESRISULTATO		VARCHAR(1000)	= '' OUTPUT
AS
BEGIN

	SET NOCOUNT ON;

BEGIN TRY
	
	IF EXISTS (SELECT * FROM TIPO_PAGAMENTO WHERE ID_PAGAMENTO = @ID_PAGAMENTO)
	BEGIN
		DELETE FROM  TIPO_PAGAMENTO WHERE ID_PAGAMENTO = @ID_PAGAMENTO	  
		SET @RISULTATO = 'OK'
		SET @DESRISULTATO = 'CANCELLAZIONE ESEGUITA CORRETTAMENTE'
	END
	else
	BEGIN
		SET @RISULTATO = 'KO'
		SET @DESRISULTATO = 'TIPO PAGAMENTO NON PRESENTE! CANCELLAZIONE NON ESEGUITA'
	END

END TRY
BEGIN CATCH
    SET @RISULTATO = 'KO'
    SET @DESRISULTATO = ERROR_MESSAGE()
END CATCH	

END