CREATE PROCEDURE [dbo].[PRC_GET_PRODOTTI]

AS
	SET NOCOUNT ON
	
	SELECT 0 as ord,0 AS ID_ARTICOLO, 'Tutti' AS PRODOTTO
	UNION	
	SELECT 1 as ord,ID_ARTICOLO,NOME + ' ' + NOME_BREVE AS PRODOTTO
	FROM ARTICOLO 
	GROUP BY ID_ARTICOLO,NOME + ' ' + NOME_BREVE 
	ORDER BY 1,3