

CREATE PROCEDURE [dbo].[PRC_GET_REPARTO]
@IDREPARTO INT = 0
AS
BEGIN
	SET NOCOUNT ON
	
    SELECT * FROM REPARTO
	WHERE STATUS = 'V'
	AND	IDREPARTO = CASE WHEN @IDREPARTO = 0 THEN IDREPARTO ELSE @IDREPARTO END  
	
END