


CREATE PROCEDURE [dbo].[PRC_INSERT_CATEGORIA]
@ID_CATEGORIA 		  INT,
@DESCRIZIONE 	      VARCHAR(200),
@DESCRIZIONE_INGLESE  VARCHAR(200),
@DESCRIZIONE_FRANCESE VARCHAR(200),
@RISULTATO			  VARCHAR(2000) OUTPUT 
AS
	SET NOCOUNT ON
	BEGIN TRY
	
		IF EXISTS(SELECT DESCRIZIONE_CATEGORIA  FROM CATEGORIA  WHERE DESCRIZIONE_CATEGORIA   = @DESCRIZIONE)
		 BEGIN
			 	UPDATE    	CATEGORIA 
				SET         DESCRIZIONE_CATEGORIA  = @DESCRIZIONE 
				WHERE 	    ID_CATEGORIA  = @ID_CATEGORIA		
			
				UPDATE    	CATEGORIA_LINGUA 
				SET         DESCRIZIONE_CATEGORIA  = @DESCRIZIONE_INGLESE 
				WHERE 	    ID_CATEGORIA  = @ID_CATEGORIA		
				AND			ID_LINGUA=2
				
				UPDATE    	CATEGORIA_LINGUA 
				SET         DESCRIZIONE_CATEGORIA  = @DESCRIZIONE_FRANCESE 
				WHERE 	    ID_CATEGORIA  = @ID_CATEGORIA		
				AND			ID_LINGUA=3
			
			SET @RISULTATO  = 'OK AGGIORNAMENTO'
		 END
		ELSE
		BEGIN
			--PRINT ' NON ESISTE CATEGORIA LA INSERISCO'
			INSERT INTO CATEGORIA (DESCRIZIONE_CATEGORIA  , STATUS ,VISUALIZZA ) 
			VALUES(@DESCRIZIONE , 'V','S')

			SET @ID_CATEGORIA = @@IDENTITY
			
			INSERT INTO CATEGORIA_LINGUA  (ID_CATEGORIA,ID_LINGUA,DESCRIZIONE_CATEGORIA)
			VALUES (@ID_CATEGORIA,2,@DESCRIZIONE_INGLESE)	
			
			INSERT INTO CATEGORIA_LINGUA  (ID_CATEGORIA,ID_LINGUA,DESCRIZIONE_CATEGORIA)
			VALUES (@ID_CATEGORIA,3,@DESCRIZIONE_FRANCESE)
			
			SET @RISULTATO  = 'OK INSERIMENTO'
		END
		
		
	END TRY
	BEGIN CATCH
		SET @RISULTATO =  'KO ' + ERROR_MESSAGE()
	END CATCH