

CREATE PROCEDURE [dbo].[PRC_DELETE_ARTICOLO]
@ID_ARTICOLO INT,
@RISULTATO CHAR(2) = '' OUTPUT,
@DESRISULTATO VARCHAR(1000) = '' OUTPUT
AS
BEGIN
SET NOCOUNT ON
BEGIN TRY
	BEGIN TRANSACTION

	UPDATE ARTICOLO SET STATUS = 'C' WHERE ID_ARTICOLO = @ID_ARTICOLO
	DELETE FROM ARTICOLO_LINGUA WHERE ID_ARTICOLO = @ID_ARTICOLO
	DELETE FROM ARTICOLO_ALLERGENE WHERE ID_ARTICOLO = @ID_ARTICOLO
	DELETE FROM ARTICOLO_INGREDIENTE WHERE ID_ARTICOLO = @ID_ARTICOLO

	SET @RISULTATO = 'OK'
	SET @DESRISULTATO = 'CANCELLAZIONE EFFETTUATA'
	COMMIT TRANSACTION
END TRY
BEGIN CATCH
	IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
	SET @RISULTATO = 'KO'
	SET @DESRISULTATO = ERROR_MESSAGE()
END CATCH
END