
CREATE PROCEDURE PRC_SET_BASKET_TAVOLO
@ID_BASKET			  INT,
@TAVOLO				  INT,
@RISULTATO			  CHAR(2) = '' OUTPUT,
@DESRISULTATO		  VARCHAR(1000)	= '' OUTPUT
AS
SET NOCOUNT ON
BEGIN TRY
	UPDATE BASKET_TESTATA SET TAVOLO = @TAVOLO WHERE ID_BASKET = @ID_BASKET
	SET @RISULTATO = 'OK'
	SET @DESRISULTATO = 'AGGIORNAMENTO EFFETTUATO'
END TRY
BEGIN CATCH
	SET @RISULTATO = 'KO'
	SET @DESRISULTATO = ERROR_MESSAGE()
END CATCH