-- =============================================
-- Author:		delpiano stefano
-- Create date: 06-05-2015
-- Description:	ricerca di uno scontrino
-- =============================================
CREATE PROCEDURE [dbo].[PRC_GET_SCONTRINO]
@NEGOZIO		VARCHAR(10),
@DATA			VARCHAR(8),
@ORA			VARCHAR(6),
@CASSA			INT,
@SCONTRINO		INT,
@FORMATOXML		CHAR(2) = 'NO'

AS
BEGIN

	SET NOCOUNT ON;

	IF @FORMATOXML = 'SI' 
	BEGIN
	
		SELECT  (
		SELECT * FROM SCONTRINATO_TESTATA WITH (NOLOCK)
				WHERE 
				CODICE_NEGOZIO	=	@NEGOZIO	AND
				DATA			=	@DATA		AND
				ORA				=	@ORA		AND
				CASSA			=	@CASSA		AND
				SCONTRINO		=	@SCONTRINO	
		FOR
		XML PATH('TESTATA'),
		TYPE
		),				
		(		
		SELECT A.*, C.NOME FROM SCONTRINATO_RIGA A WITH (NOLOCK)
		LEFT JOIN GIACENZA B WITH (NOLOCK)
		ON (A.CODICE_NEGOZIO = B.CODICE_NEGOZIO
		AND A.EAN = B.EAN)  
		LEFT JOIN ARTICOLO C WITH (NOLOCK) 
		ON (B.ID_ARTICOLO = C.ID_ARTICOLO)
				WHERE 
				A.CODICE_NEGOZIO	=	@NEGOZIO	AND
				DATA				=	@DATA		AND
				ORA					=	@ORA		AND
				CASSA				=	@CASSA		AND
				SCONTRINO			=	@SCONTRINO	
		FOR
		XML PATH('RIGHE'),
		TYPE
		),				
		(		
		SELECT * FROM SCONTRINATO_PAGAMENTO WITH (NOLOCK)
				WHERE 
				CODICE_NEGOZIO	=	@NEGOZIO	AND
				DATA			=	@DATA		AND
				ORA				=	@ORA		AND
				CASSA			=	@CASSA		AND
				SCONTRINO		=	@SCONTRINO	
		FOR
		XML PATH('PAGAMENTO'),
		TYPE
		)
		FOR XML PATH(''),
		ROOT('SCONTRINO')			
		
	END

	ELSE

	BEGIN
	
		SELECT * FROM SCONTRINATO_TESTATA WITH (NOLOCK)
				WHERE 
				CODICE_NEGOZIO	=	@NEGOZIO	AND
				DATA			=	@DATA		AND
				ORA				=	@ORA		AND
				CASSA			=	@CASSA		AND
				SCONTRINO		=	@SCONTRINO	
				
		SELECT A.*, C.NOME FROM SCONTRINATO_RIGA A WITH (NOLOCK)
		LEFT JOIN GIACENZA B WITH (NOLOCK)
		ON (A.CODICE_NEGOZIO = B.CODICE_NEGOZIO
		AND A.EAN = B.EAN)  
		LEFT JOIN ARTICOLO C WITH (NOLOCK) 
		ON (B.ID_ARTICOLO = C.ID_ARTICOLO)
				WHERE 
				A.CODICE_NEGOZIO	=	@NEGOZIO	AND
				DATA				=	@DATA		AND
				ORA					=	@ORA		AND
				CASSA				=	@CASSA		AND
				SCONTRINO			=	@SCONTRINO	
				
		SELECT * FROM SCONTRINATO_PAGAMENTO WITH (NOLOCK)
				WHERE 
				CODICE_NEGOZIO	=	@NEGOZIO	AND
				DATA			=	@DATA		AND
				ORA				=	@ORA		AND
				CASSA			=	@CASSA		AND
				SCONTRINO		=	@SCONTRINO	
				
	END
END