
CREATE PROCEDURE [dbo].[PRC_CHECK_DELETE_ALLERGENE]
@ID_ALLERGENE INT = 0,
@CTR INT = 0 OUTPUT
AS
BEGIN
	SELECT @CTR = COUNT(*) FROM ARTICOLO_ALLERGENE WHERE ID_ALLERGENE = @ID_ALLERGENE
	RETURN @CTR
END