
CREATE PROCEDURE PRC_UPDATE_BASKET_QTA_INVIATA
@ID_BASKET			  INT,
@RISULTATO			  CHAR(2) = '' OUTPUT,
@DESRISULTATO		  VARCHAR(1000)	= '' OUTPUT
AS
SET NOCOUNT ON
BEGIN TRY
	UPDATE BASKET_RIGA SET QTA_INVIATA = QTA WHERE ID_BASKET = @ID_BASKET

	SET @RISULTATO = 'OK'
	SET @DESRISULTATO = 'INSERIMENTO EFFETTUATO CORRETTAMENTE'
END TRY
BEGIN CATCH
	SET @RISULTATO = 'KO'
	SET @DESRISULTATO = ERROR_MESSAGE()
END CATCH