-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[PRC_INSERT_UPD_USER_NEGOZIO]

@CODICE_NEGOZIO VARCHAR(10) = '001' , 
@USERID 	   INT				= 0 ,
@NOME    	   VARCHAR(64)		= '',
@COGNOME       VARCHAR(64)	    = '', 
@EAN 		   NVARCHAR(13)		= '', 
@PUOSCONTARE   NCHAR(2)      	= '',
@RISULTATO			    CHAR(2)			= '' OUTPUT,
@DESRISULTATO	    	VARCHAR(1000)	= '' OUTPUT
AS  
BEGIN

	SET NOCOUNT ON;

BEGIN TRY
	
	BEGIN TRANSACTION 
	


		IF EXISTS(SELECT USERID  FROM  USER_NEGOZIO  WHERE   USERID=@USERID  AND CODICE_NEGOZIO=@CODICE_NEGOZIO )		
			BEGIN
				UPDATE USER_NEGOZIO
					SET 
					CODICE_NEGOZIO=@CODICE_NEGOZIO,
                    USERID=@USERID, 
					NOME=@NOME,    	   
					COGNOME=@COGNOME,      
					EAN=@EAN,  		  
					PUOSCONTARE=@PUOSCONTARE 
					
				WHERE USERID = @USERID 
				
				SET @RISULTATO		= 'OK' 
				SET @DESRISULTATO	= 'TUTTO OK'	
			END
		ELSE
		BEGIN
				IF NOT EXISTS(SELECT USERID	 FROM  USER_NEGOZIO WHERE USERID=@USERID  AND CODICE_NEGOZIO=@CODICE_NEGOZIO )
				BEGIN
				
					INSERT INTO USER_NEGOZIO
						(CODICE_NEGOZIO, USERID,  NOME, COGNOME, EAN, PUOSCONTARE)
					VALUES
						(@CODICE_NEGOZIO, @USERID, @NOME, @COGNOME, @EAN, @PUOSCONTARE)
							
					SET @RISULTATO		= 'OK' 
					SET @DESRISULTATO	= 'TUTTO OK'
				END	
				ELSE
				BEGIN
				    SET @RISULTATO		= 'KO' 
					SET @DESRISULTATO	= 'CODICE USER ID PREESISTENTE'	
				END
		END	

END TRY
BEGIN CATCH
    SET @RISULTATO = 'KO'
	SET @DESRISULTATO = ERROR_MESSAGE()
END CATCH
		
IF @RISULTATO = 'OK' 
	COMMIT TRANSACTION
ELSE
	ROLLBACK TRANSACTION
END