
-- =============================================
-- Author:		DELPIANO STEFANO
-- Create date: 23-02-2014
-- Description: registrazione pagamento
-- ATTENZIONE : SE PREVISTO DAL CONFIG SOTTRAE ANCHE LE GIACENZE
-- =============================================
CREATE PROCEDURE [dbo].[PRC_BASKET_PAGATO]
@ID_BASKET			int,
@TIPOPAGAMENTO		VARCHAR(10),
@IMPORTO			MONEY,
@RISULTATO			CHAR(2)			= '' OUTPUT,
@DESRISULTATO		VARCHAR(1000)	= '' OUTPUT
AS
BEGIN

	SET NOCOUNT ON;
	

	BEGIN TRY
	
	BEGIN TRANSACTION 
	
	DECLARE @CODICE_NEGOZIO		VARCHAR(10)
	DECLARE @GESTISCIGIACENZA	VARCHAR(2)
	
	SET		@CODICE_NEGOZIO   = 'XXXX'
	SET		@GESTISCIGIACENZA = 'NO'
	SELECT	@CODICE_NEGOZIO	  = CODICE_NEGOZIO FROM BASKET_TESTATA WHERE ID_BASKET = @ID_BASKET
	SELECT	@GESTISCIGIACENZA = VALORE FROM APP_SETUP WHERE CHIAVE = 'GESTISCIGIACENZA_' + @CODICE_NEGOZIO
	

	UPDATE [BASKET_TESTATA]
           SET [PAGATO] = 'S'
	WHERE	[ID_BASKET] = @ID_BASKET
	
	IF EXISTS(SELECT * FROM [BASKET_PAGAMENTO] WHERE [ID_BASKET] = @ID_BASKET AND ([TIPO_PAGAMENTO] = 'xx' or [TIPO_PAGAMENTO] = @TIPOPAGAMENTO))  
	UPDATE [BASKET_PAGAMENTO]
           SET [TIPO_PAGAMENTO] = @TIPOPAGAMENTO,[IMPORTO] = @IMPORTO
	WHERE	[ID_BASKET] = @ID_BASKET
	ELSE
	INSERT INTO [BASKET_PAGAMENTO] VALUES(@ID_BASKET,@TIPOPAGAMENTO,@IMPORTO)
		
	IF	@GESTISCIGIACENZA = 'SI'
	BEGIN
	
		EXECUTE PRC_GIACENZA_SOTTRAI_BASKET @ID_BASKET	
	END
    SET @RISULTATO = 'OK'
    SET @DESRISULTATO = 'OK'
END TRY
BEGIN CATCH

    PRINT 'VADO IN ERRORE'
    SET @RISULTATO = 'KO'
    SET @DESRISULTATO = ERROR_MESSAGE()
END CATCH	

	FINE:
	PRINT @RISULTATO
	PRINT @DESRISULTATO
	
	IF SUBSTRING(@RISULTATO, 1 , 2) = 'OK' 
		COMMIT TRANSACTION
	ELSE
		ROLLBACK TRANSACTION
		




END