
CREATE PROCEDURE [dbo].[PRC_CANCELLA_COMANDA]
--@CODICE_NEGOZIO 	VARCHAR(10)		= '',
--@STATUS				VARCHAR(10)		= '',
@RISULTATO			CHAR(2)			= '' OUTPUT,
@DESRISULTATO		VARCHAR(1000)	= '' OUTPUT
AS
BEGIN

	SET NOCOUNT ON;

BEGIN TRY
	
	BEGIN TRANSACTION 		

	--IF @STATUS = '' 
	--BEGIN
		DELETE COMANDA_TESTATA
		DELETE COMANDA_RIGA
	--END
	/*
	UPDATE  PROGRESSIVO
		SET PROGR = 0 WHERE CODICE = 'COMANDA' and CODICE_NEGOZIO = @CODICE_NEGOZIO
			*/	 		
	SET @RISULTATO = 'OK'
	SET @DESRISULTATO = 'CANCELLAZIONE ESEGUITA CORRETTAMENTE'

END TRY
BEGIN CATCH
    SET @RISULTATO = 'KO ' + ERROR_MESSAGE()
    SET @DESRISULTATO = ERROR_MESSAGE()
END CATCH	

	IF SUBSTRING(@RISULTATO, 1 , 2) = 'OK' 
		COMMIT TRANSACTION
	ELSE
		ROLLBACK TRANSACTION
		
END