
CREATE PROCEDURE [dbo].[PRC_INSERT_BASKET_RIGA]
@ID_BASKET			  INT,
@ID_MENU			  INT,
@ID_ARTICOLO		  INT,
@PREZZO				  MONEY,
@QTA				  INT,
@ISTRUZIONI			  VARCHAR(250),
@BOX				  INT,
@RISULTATO			  CHAR(2) = '' OUTPUT,
@DESRISULTATO		  VARCHAR(1000)	= '' OUTPUT
AS
SET NOCOUNT ON
BEGIN TRY
	
	MERGE INTO BASKET_RIGA AS TARGET
	USING (SELECT @ID_BASKET, @ID_MENU, @ID_ARTICOLO, @PREZZO, @QTA, @ISTRUZIONI, @BOX)
		  AS SOURCE(ID_BASKET, ID_MENU, ID_ARTICOLO, PREZZO, QTA, ISTRUZIONI, BOX)
	ON SOURCE.ID_BASKET = TARGET.ID_BASKET AND SOURCE.ID_MENU = TARGET.ID_MENU AND SOURCE.ID_ARTICOLO = TARGET.ID_ARTICOLO
	WHEN MATCHED THEN UPDATE SET PREZZO = SOURCE.PREZZO,
								 QTA = SOURCE.QTA,
								 ISTRUZIONI = SOURCE.ISTRUZIONI,
								 BOX = SOURCE.BOX
	WHEN NOT MATCHED THEN INSERT (ID_BASKET, ID_MENU, ID_ARTICOLO, PREZZO, QTA, ISTRUZIONI, BOX)
						  VALUES (SOURCE.ID_BASKET, SOURCE.ID_MENU, SOURCE.ID_ARTICOLO, SOURCE.PREZZO, SOURCE.QTA, SOURCE.ISTRUZIONI, SOURCE.BOX)
	;--WHEN NOT MATCHED BY SOURCE AND TARGET.ID_BASKET = @ID_BASKET AND TARGET.ID_MENU = @ID_MENU AND TARGET.ID_ARTICOLO = @ID_ARTICOLO THEN DELETE;
	
	SET @RISULTATO = 'OK'
	SET @DESRISULTATO = 'INSERIMENTO EFFETTUATO CORRETTAMENTE'
		
END TRY
BEGIN CATCH
	SET @RISULTATO = 'KO'
	SET @DESRISULTATO = ERROR_MESSAGE()
END CATCH