-- =============================================
-- =============================================
CREATE PROCEDURE [dbo].[PRC_DELETE_CANALE]
@COD_NEGOZIO         VARCHAR(10)	= '',
@COD_CANALE_VENDITA  VARCHAR(10)	= '', 
@RISULTATO		     CHAR(2)		= '' OUTPUT,
@DESRISULTATO	     VARCHAR(1000)	= '' OUTPUT
AS
BEGIN

	SET NOCOUNT ON;

BEGIN TRY
	
	BEGIN TRANSACTION 		
	
	IF EXISTS (SELECT * FROM CANALE_VENDITA WHERE  COD_NEGOZIO =@COD_NEGOZIO AND  COD_CANALE_VENDITA= @COD_CANALE_VENDITA  )
	BEGIN
		DELETE FROM  CANALE_VENDITA WHERE COD_NEGOZIO =@COD_NEGOZIO AND COD_CANALE_VENDITA= @COD_CANALE_VENDITA 	  
		SET @RISULTATO = 'OK'
		SET @DESRISULTATO = 'CANCELLAZIONE ESEGUITA CORRETTAMENTE'
	END

END TRY
BEGIN CATCH
    SET @RISULTATO = 'KO ' + ERROR_MESSAGE()
    SET @DESRISULTATO = ERROR_MESSAGE()
END CATCH	

	FINE:

	IF SUBSTRING(@RISULTATO, 1 , 2) = 'OK' 
		COMMIT TRANSACTION
	ELSE
		ROLLBACK TRANSACTION
		
END