

CREATE PROCEDURE [dbo].[PRC_INSERT_UPD_CATEGORIA_old]
@ID_PROGRESSIVO 	  INT,
@ORDINE			 	  INT,
@DESCRIZIONE 	      VARCHAR(200),
@DESCRIZIONE_INGLESE  VARCHAR(200),
@DESCRIZIONE_FRANCESE VARCHAR(200),
@RISULTATO			  VARCHAR(2000) OUTPUT 
AS
	SET NOCOUNT ON
	BEGIN TRY
	
		BEGIN TRANSACTION 
		
		IF @ORDINE=0 OR @ORDINE=NULL 
		BEGIN
			SELECT  @ORDINE=MAX(ORDINE)+1 FROM CATEGORIA_old
		END 
		--IF EXISTS(SELECT DESCRIZIONE_CATEGORIA  FROM CATEGORIA_old  WHERE @DESCRIZIONE   = @DESCRIZIONE )
	--	ELSE BEGIN
		
		IF EXISTS(SELECT DESCRIZIONE_CATEGORIA  FROM CATEGORIA_old  WHERE ID_CATEGORIA= @ID_PROGRESSIVO )
		 BEGIN
			 	UPDATE    	CATEGORIA_old 
				SET         DESCRIZIONE_CATEGORIA  = @DESCRIZIONE ,
							ORDINE= @ORDINE
				WHERE 	    ID_CATEGORIA  = @ID_PROGRESSIVO		
			
				IF EXISTS(SELECT DESCRIZIONE_CATEGORIA  FROM CATEGORIA_LINGUA  WHERE ID_CATEGORIA= @ID_PROGRESSIVO )
				BEGIN
					UPDATE    	CATEGORIA_LINGUA 
					SET         DESCRIZIONE_CATEGORIA  = @DESCRIZIONE_INGLESE 
					WHERE 	    ID_CATEGORIA  = @ID_PROGRESSIVO		
					AND			ID_LINGUA=2
				END
				ELSE	
				BEGIN			
					INSERT INTO CATEGORIA_LINGUA  (ID_CATEGORIA,ID_LINGUA,DESCRIZIONE_CATEGORIA)
					VALUES (@ID_PROGRESSIVO,2,@DESCRIZIONE_INGLESE)		
				END
				
				IF EXISTS(SELECT DESCRIZIONE_CATEGORIA  FROM CATEGORIA_old  WHERE ID_CATEGORIA= @ID_PROGRESSIVO )
				BEGIN
					UPDATE    	CATEGORIA_LINGUA 
					SET         DESCRIZIONE_CATEGORIA  = @DESCRIZIONE_INGLESE 
					WHERE 	    ID_CATEGORIA  = @ID_PROGRESSIVO		
					AND			ID_LINGUA=3
				END		
				ELSE
				BEGIN
					INSERT INTO CATEGORIA_LINGUA  (ID_CATEGORIA,ID_LINGUA,DESCRIZIONE_CATEGORIA)
					VALUES (@ID_PROGRESSIVO,3,@DESCRIZIONE_FRANCESE)
				END
			
	--		SET @RISULTATO  = 'KO DESCRIZIONE PREESISTENTE'		
			SET @RISULTATO  = 'OK AGGIORNAMENTO'		
		 END
		ELSE
		BEGIN
			--PRINT ' NON ESISTE PROGRESSIVO LO INSERISCO'
			IF EXISTS(SELECT DESCRIZIONE_CATEGORIA  FROM CATEGORIA_old  WHERE DESCRIZIONE_CATEGORIA   = @DESCRIZIONE )
			BEGIN
				SET @RISULTATO  = 'KO DESCRIZIONE PREESISTENTE'		
			END 
			ELSE BEGIN
			INSERT INTO CATEGORIA_old (ID_CATEGORIA  , ORDINE , DESCRIZIONE_CATEGORIA  , STATUS ,VISUALIZZA ) 
			VALUES(@ID_PROGRESSIVO , @ORDINE ,@DESCRIZIONE , 'V','S')
			
			INSERT INTO CATEGORIA_LINGUA  (ID_CATEGORIA,ID_LINGUA,DESCRIZIONE_CATEGORIA)
			VALUES (@ID_PROGRESSIVO,2,@DESCRIZIONE_INGLESE)	
			
			INSERT INTO CATEGORIA_LINGUA  (ID_CATEGORIA,ID_LINGUA,DESCRIZIONE_CATEGORIA)
			VALUES (@ID_PROGRESSIVO,3,@DESCRIZIONE_FRANCESE)
			
			SET @RISULTATO  = 'OK INSERIMENTO'
			END
		END
	--	END
		
	END TRY
	BEGIN CATCH
		SET @RISULTATO =  'KO ' + ERROR_MESSAGE()
	END CATCH



	IF @RISULTATO like 'OK%' 
		COMMIT TRANSACTION
	ELSE
		ROLLBACK TRANSACTION