
CREATE PROCEDURE [dbo].[PRC_CHECK_DELETE_INGREDIENTE]
@ID_INGREDIENTE INT = 0,
@CTR INT = 0 OUTPUT
AS
BEGIN
	SELECT @CTR = COUNT(*) FROM ARTICOLO_INGREDIENTE WHERE ID_INGREDIENTE = @ID_INGREDIENTE
	RETURN @CTR
END