-- =============================================
-- Author:		DELPIANO STEFANO
-- Create date: 26-06-2015
-- Description: SALVATAGGIO TALLONCINI BILANCIA
-- =============================================
CREATE PROCEDURE [dbo].[PRC_TALLONCINO_REGISTRA]
@DOCXML				ntext
AS
BEGIN

	DECLARE @PROG	INT
	DECLARE @RISULTATO VARCHAR(2)
	SET NOCOUNT ON;


	
	DECLARE		@HDOC 		INT  
	
	EXEC 		SP_XML_PREPAREDOCUMENT @HDOC OUTPUT,@DOCXML

	SELECT * into #TALL
	FROM OPENXML(@HDOC, 'TALLONCINO/SCOBIL/R',2)   
	WITH 
		(
		NEGOZIO		varchar(10),
		EANSCO		varchar(13)
		)

	
		
	EXEC SP_XML_REMOVEDOCUMENT @HDOC	
	


BEGIN TRY
	
	BEGIN TRANSACTION 
	

	

	print 'inserisco testata'	
	INSERT INTO [TALLONCINO_BILANCIA]
           ([NEGOZIO]
           ,[EAN_TALLONCINO]
           ,[TRASFERITO]
           )
     SELECT
           A.NEGOZIO,
           EANSCO,
           'N'
     FROM #TALL A LEFT JOIN [TALLONCINO_BILANCIA] B ON A.NEGOZIO = B.NEGOZIO AND EANSCO = EAN_TALLONCINO WHERE EAN_TALLONCINO IS NULL
		 		
	SET @RISULTATO = 'OK'



END TRY
BEGIN CATCH
    --IF @@TRANCOUNT > 0
    --    ROLLBACK TRAN --ROLLBACK IN CASE OF ERROR

    -- YOU CAN RAISE ERROR WITH RAISEERROR() STATEMENT INCLUDING THE DETAILS OF THE EXCEPTION
    --RAISERROR(ERROR_MESSAGE(), ERROR_SEVERITY(), 1)
    PRINT 'VADO IN ERRORE'
    SET @RISULTATO = 'KO ' + ERROR_MESSAGE()

END CATCH	

	FINE:
	PRINT @RISULTATO

	
	IF SUBSTRING(@RISULTATO, 1 , 2) = 'OK' 
		COMMIT TRANSACTION
	ELSE
		ROLLBACK TRANSACTION
		




END