

CREATE PROCEDURE [dbo].[PRC_GET_CATEGORIA]
 @ID_CATEGORIA	INT=0,
 @ID_LINGUA		INT=0
AS
	SET NOCOUNT ON
	
	SELECT DISTINCT	c.ID_CATEGORIA, 
	case when @ID_LINGUA = 2 then isnull(en.DESCRIZIONE_CATEGORIA, c.DESCRIZIONE_CATEGORIA) 
	     when @ID_LINGUA = 3 then isnull(fr.DESCRIZIONE_CATEGORIA, c.DESCRIZIONE_CATEGORIA) 
	     else c.DESCRIZIONE_CATEGORIA end as DESCRIZIONE_CATEGORIA, 
	case when @ID_LINGUA = 2 then isnull(en.IMMAGINE, c.IMMAGINE)
	     when @ID_LINGUA = 3 then isnull(fr.IMMAGINE, c.IMMAGINE)
	     else c.IMMAGINE end as IMMAGINE, 
	c.STATUS, c.ORDINE, c.VISUALIZZA
	FROM	CATEGORIA  c
		left join CATEGORIA_LINGUA en on (c.ID_CATEGORIA = en.ID_CATEGORIA and en.ID_LINGUA = 2)
		left join CATEGORIA_LINGUA fr on (c.ID_CATEGORIA = en.ID_CATEGORIA and fr.ID_LINGUA = 3)
	WHERE c.STATUS = 'V' and 
	c.ID_CATEGORIA =	CASE WHEN @ID_CATEGORIA = 0 THEN c.ID_CATEGORIA ELSE @ID_CATEGORIA END