
CREATE PROCEDURE [dbo].[PRC_DELETE_ALLERGENE]
@ID_ALLERGENE INT,
@RISULTATO CHAR(2) = '' OUTPUT,
@DESRISULTATO VARCHAR(1000) = '' OUTPUT
AS
BEGIN
SET NOCOUNT ON
BEGIN TRY
	BEGIN TRANSACTION

	DELETE FROM ALLERGENE WHERE ID_ALLERGENE = @ID_ALLERGENE
	DELETE FROM ARTICOLO_ALLERGENE WHERE ID_ALLERGENE = @ID_ALLERGENE
	SET @RISULTATO = 'OK'
	SET @DESRISULTATO = 'CANCELLAZIONE EFFETTUATA'
	
	COMMIT TRANSACTION 

END TRY
BEGIN CATCH
	IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
	SET @RISULTATO = 'KO'
	SET @DESRISULTATO = ERROR_MESSAGE()
END CATCH
END