
CREATE PROCEDURE [dbo].[PRC_INSERT_UPD_ARTICOLO_old]

@PROG				INT				= 0,
@CODICE_ARTICOLO	VARCHAR(20)     = '', 
@NOME				VARCHAR(250)	= '',
@NOME_BREVE			VARCHAR(25)		= '',
@DESCRIZIONE		VARCHAR(250)	= '',

@CATEGORIA			INT				= 0,
@REPARTO			INT				= 0,

@PREZZO				MONEY			= 0, -- Prezzo Base
@QTA				DECIMAL(8,3)    = 0, -- Quantità in Giacenza
@CODICE_UM			VARCHAR(3)      = 'UN', -- Default: Unitario
@TIPO_ARTICOLO		CHAR(1)			= 'S',  -- Default: Semplice
@CODICE_ARTICOLO_PRINCIPALE	VARCHAR(20)     = '', 
@QTA_ARTICOLO_PRINCIPALE	DECIMAL(8,3)    = 0,
@CODICE_UM_ARTICOLO_PRINCIPALE VARCHAR(3) = "UN",
@DEFAULT_IMAGE VARCHAR(250) = "",

@STATUS				VARCHAR(10)		= '',

@NEGOZIO			VARCHAR(10)		= '',

@RISULTATO			CHAR(2)			= '' OUTPUT,
@DESRISULTATO		VARCHAR(1000)	= '' OUTPUT
AS
BEGIN

	SET NOCOUNT ON;

BEGIN TRY
	
	BEGIN TRANSACTION 
	


		IF EXISTS(SELECT NOME FROM ARTICOLO WHERE ID_ARTICOLO 	 = @PROG  )		
			BEGIN
				UPDATE ARTICOLO
					SET 
					CODICE_ARTICOLO = @CODICE_ARTICOLO, 
					NOME = @NOME, NOME_BREVE = @NOME_BREVE, DESCRIZIONE = @DESCRIZIONE, 
					CODICE_UM = @CODICE_UM, PREZZO_BASE = @PREZZO,
					ID_CATEGORIA = @CATEGORIA, REPARTO = @REPARTO,
					TIPO_ARTICOLO = @TIPO_ARTICOLO, 
					CODICE_ARTICOLO_PRINCIPALE = @CODICE_ARTICOLO_PRINCIPALE,
					QTA_ARTICOLO_PRINCIPALE = @QTA_ARTICOLO_PRINCIPALE, 
					CODICE_UM_ARTICOLO_PRINCIPALE = @CODICE_UM_ARTICOLO_PRINCIPALE, 
					DEFAULT_IMAGE = @DEFAULT_IMAGE,
					STATUS = @STATUS,
					REPARTO_VENDITA = @REPARTO -- agguinto durante la creazione di un prodotto da menu, anche in UPDATE
				WHERE ID_ARTICOLO = @PROG 
				
				UPDATE GIACENZA 
					SET GIACENZA  = @QTA
				WHERE CODICE_NEGOZIO = @NEGOZIO AND ID_ARTICOLO = @PROG
				SET @RISULTATO		= 'OK' 
				SET @DESRISULTATO	= 'TUTTO OK'	
			END
		ELSE
		BEGIN
				IF NOT EXISTS(SELECT CODICE_ARTICOLO FROM ARTICOLO WHERE CODICE_ARTICOLO = @CODICE_ARTICOLO)
				BEGIN
				
					INSERT INTO ARTICOLO
						(ID_ARTICOLO, CODICE_ARTICOLO, NOME, NOME_BREVE, DESCRIZIONE, ID_CATEGORIA, DEFAULT_IMAGE, QTA_MINIMA, CODICE_IVA, PREZZO_BASE, REPARTO, STATUS, CODICE_UM, TIPO_ARTICOLO, CODICE_ARTICOLO_PRINCIPALE, QTA_ARTICOLO_PRINCIPALE, CODICE_UM_ARTICOLO_PRINCIPALE, REPARTO_VENDITA)
					VALUES
						(@PROG,	@CODICE_ARTICOLO, @NOME, @NOME_BREVE, @DESCRIZIONE, @CATEGORIA, @DEFAULT_IMAGE, 999, ' ', @PREZZO, @REPARTO, @STATUS, @CODICE_UM, @TIPO_ARTICOLO, @CODICE_ARTICOLO_PRINCIPALE, @QTA_ARTICOLO_PRINCIPALE, @CODICE_UM_ARTICOLO_PRINCIPALE, @REPARTO)
							
					INSERT INTO GIACENZA
						(CODICE_NEGOZIO, EAN, ID_ARTICOLO, GIACENZA, RIORDINO)
					VALUES
						(@NEGOZIO, @PROG, @PROG, @QTA, 999)
					SET @RISULTATO		= 'OK' 
					SET @DESRISULTATO	= 'TUTTO OK'
				END	
				ELSE
				BEGIN
				    SET @RISULTATO		= 'KO' 
					SET @DESRISULTATO	= 'CODICE ARTICOLO ESTERNO PREESISTENTE'	
				END
		END	

END TRY
BEGIN CATCH
    SET @RISULTATO = 'KO'
	SET @DESRISULTATO = ERROR_MESSAGE()
END CATCH
		
IF @RISULTATO = 'OK' 
	COMMIT TRANSACTION
ELSE
	ROLLBACK TRANSACTION
END