-- =============================================
-- Author:		DELPIANO
-- Create date: 01-01-2017
-- Description:	ESTRAZIONE DATI DA INVIARE
-- =============================================
CREATE PROCEDURE [dbo].[PRC_AGGIORNAMENTO_DA_INVIARE_INSERT]
@KEY	VARCHAR(50),	
@TIPO	VARCHAR(50)
AS
BEGIN

	SET NOCOUNT ON;


	DECLARE @DOC	XML

	IF @TIPO = 'ARTICOLO'
	BEGIN
		-- ARTICOLO + ARTICOLO_LINGUA
		IF EXISTS(SELECT * FROM ARTICOLO  WITH (NOLOCK) WHERE ID_ARTICOLO = @KEY)
		BEGIN
			DECLARE @ART	XML
			DECLARE @ARTLIN	XML
			DECLARE @TOTART	XML
			SELECT @ART =
				(
					SELECT * FROM ARTICOLO  WITH (NOLOCK)
							WHERE 
							ID_ARTICOLO = @KEY	
					FOR
					XML PATH('ARTICOLO') ,
					TYPE
				)
				
				
				
			SELECT @ARTLIN =			
				(		
					SELECT * FROM ARTICOLO_LINGUA 
							WHERE 
							ID_ARTICOLO = @KEY
					FOR
					XML PATH('ARTICOLO_LINGUA') ,
					TYPE
				) 
				
				SELECT @TOTART =
				( 
				SELECT @ART AS ART, @ARTLIN AS LINGUE
				FOR XML PATH(''),
				ROOT('TOTARTICOLO')	
				)
				
				
				INSERT INTO AGGIORNAMENTO_DA_INVIARE (NEG,TABELLA,DOCXML)
				SELECT CODICE_NEGOZIO, 'ARTICOLO' AS TIPO , @TOTART AS DOCXML FROM NEGOZIO 
		END
	END
			
		 
	IF @TIPO = 'CATEGORIA'
	BEGIN
		-- CATEGORIA + CATEGORIA_LINGUA
		IF EXISTS(SELECT * FROM CATEGORIA  WITH (NOLOCK) WHERE ID_CATEGORIA = @KEY)
		BEGIN

			DECLARE @CAT	XML
			DECLARE @CATLIN	XML
			DECLARE @TOTCAT	XML
			SELECT @CAT =
				(
					SELECT * FROM CATEGORIA  WITH (NOLOCK)
							WHERE 
							ID_CATEGORIA = @KEY	
					FOR
					XML PATH('CATEGORIA') ,
					TYPE
				)
				
				
				
			SELECT @CATLIN =			
				(		
					SELECT * FROM CATEGORIA_LINGUA 
							WHERE 
							ID_CATEGORIA = @KEY
					FOR
					XML PATH('CATEGORIA_LINGUA') ,
					TYPE
				) 
				
				SELECT @TOTCAT =
				( 
				SELECT @CAT AS CAT, @CATLIN AS LINGUE
				FOR XML PATH(''),
				ROOT('TOTCATEGORIA')	
				)
		

				INSERT INTO AGGIORNAMENTO_DA_INVIARE (NEG,TABELLA,DOCXML)
				SELECT CODICE_NEGOZIO, 'CATEGORIA' AS TIPO , @TOTCAT AS DOCXML FROM NEGOZIO 
		END					
	END				
		 
		 
	IF @TIPO = 'LINGUA'
	BEGIN
		-- LINGUA	
		IF EXISTS(SELECT * FROM LINGUA  WITH (NOLOCK) WHERE ID_LINGUA = @KEY)
		BEGIN
			SELECT @DOC =
				(
					SELECT * FROM LINGUA  WITH (NOLOCK)
							WHERE 
							ID_LINGUA  = @KEY	
					FOR
					XML PATH('LINGUA') ,
					TYPE
				)

				INSERT INTO AGGIORNAMENTO_DA_INVIARE (NEG,TABELLA,DOCXML)
				SELECT CODICE_NEGOZIO, 'LINGUA' AS TIPO , @DOC AS DOCXML FROM NEGOZIO
		END		
	END					 
		 
		 
	IF @TIPO = 'REPARTO'
	BEGIN
		-- REPARTO	
		IF EXISTS(SELECT * FROM REPARTO  WITH (NOLOCK) WHERE IDREPARTO = @KEY)
		BEGIN
			SELECT @DOC =
				(
					SELECT * FROM REPARTO  WITH (NOLOCK)
							WHERE 
							IDREPARTO  = @KEY	
					FOR
					XML PATH('REPARTO') ,
					TYPE
				)

				INSERT INTO AGGIORNAMENTO_DA_INVIARE (NEG,TABELLA,DOCXML)
				SELECT CODICE_NEGOZIO, 'REPARTO' AS TIPO , @DOC AS DOCXML FROM NEGOZIO

		END		
	END				 
		 
		 
	IF @TIPO = 'SOTTOCANALE'
	BEGIN
		-- SOTTOCANALE	
		IF EXISTS(SELECT * FROM SOTTOCANALE  WITH (NOLOCK) WHERE ID_SOTTOCANALE = @KEY)
		BEGIN
			SELECT @DOC =
				(
					SELECT * FROM SOTTOCANALE   WITH (NOLOCK)
							WHERE 
							ID_SOTTOCANALE   = @KEY	
					FOR
					XML PATH('SOTTOCANALE') ,
					TYPE
				)

				INSERT INTO AGGIORNAMENTO_DA_INVIARE (NEG,TABELLA,DOCXML)
				SELECT CODICE_NEGOZIO, 'SOTTOCANALE' AS TIPO , @DOC AS DOCXML FROM NEGOZIO
		END
				
	END				 
	
	 
	IF @TIPO = 'STATUS'
	BEGIN
		-- STATUS	
		IF EXISTS(SELECT * FROM STATUS  WITH (NOLOCK) WHERE STATUS_COD = @KEY)
		BEGIN
			SELECT @DOC =
				(
					SELECT * FROM STATUS   WITH (NOLOCK)
							WHERE 
							STATUS_COD   = @KEY	
					FOR
					XML PATH('STATUS') ,
					TYPE
				)
				
				INSERT INTO AGGIORNAMENTO_DA_INVIARE (NEG,TABELLA,DOCXML)
				SELECT CODICE_NEGOZIO, 'STATUS' AS TIPO , @DOC AS DOCXML FROM NEGOZIO
		END
				
	END				
	
	
	 
	IF @TIPO = 'TIPO_PAGAMENTO'
	BEGIN
		-- TIPO_PAGAMENTO	
		IF EXISTS(SELECT * FROM TIPO_PAGAMENTO  WITH (NOLOCK) WHERE CODICE_PAGAMENTO = @KEY)
		BEGIN
			SELECT @DOC =
				(
					SELECT * FROM TIPO_PAGAMENTO   WITH (NOLOCK)
							WHERE 
							CODICE_PAGAMENTO   = @KEY	
					FOR
					XML PATH('TIPO_PAGAMENTO') ,
					TYPE
				)
				
				INSERT INTO AGGIORNAMENTO_DA_INVIARE (NEG,TABELLA,DOCXML)
				SELECT CODICE_NEGOZIO, 'TIPO_PAGAMENTO' AS TIPO , @DOC AS DOCXML FROM NEGOZIO
		END
				
	END		
	
	 
	IF @TIPO = 'UNITA_MISURA'
	BEGIN
		-- UNITA_MISURA	
		IF EXISTS(SELECT * FROM UNITA_MISURA  WITH (NOLOCK) WHERE CODICE_UM = @KEY)
		BEGIN
		SELECT @DOC =
			(
				SELECT * FROM UNITA_MISURA   WITH (NOLOCK)
						WHERE 
						CODICE_UM   = @KEY	
				FOR
				XML PATH('UNITA_MISURA') ,
				TYPE
			)

			INSERT INTO AGGIORNAMENTO_DA_INVIARE (NEG,TABELLA,DOCXML)
			SELECT CODICE_NEGOZIO, 'UNITA_MISURA' AS TIPO , @DOC AS DOCXML FROM NEGOZIO
		END
				
	END	
	
	 
	IF @TIPO = 'GIACENZA'
	BEGIN
		-- GIACENZA
		IF EXISTS(SELECT * FROM GIACENZA  WITH (NOLOCK) WHERE EAN = @KEY)
		BEGIN
		SELECT @DOC =
			(
				SELECT * FROM GIACENZA   WITH (NOLOCK)
						WHERE 
						EAN   = @KEY	
				FOR
				XML PATH('GIACENZA') ,
				TYPE
			)

			INSERT INTO AGGIORNAMENTO_DA_INVIARE (NEG,TABELLA,DOCXML)
			SELECT CODICE_NEGOZIO, 'GIACENZA' AS TIPO , @DOC AS DOCXML FROM NEGOZIO
		END
				
	END	
	
END