-- =============================================
-- Author:		DELPIANO STEFANO	
-- Create date: 25-02-2013
-- Description:	RICERCA DELLE COMANDE 
--				sia il basket che le ha generate che lo stato in cui si trovano
--				sono parametri facoltativi
-- =============================================
CREATE PROCEDURE [dbo].[PRC_COMANDA_RICERCA]
@ID_BASKET			INT				=0,
@ID_COMANDA			INT				=0,
@STATUS				VARCHAR(10)		= '',
@RISULTATO			CHAR(2)			= '' OUTPUT,
@DESRISULTATO		VARCHAR(1000)	= '' OUTPUT
AS
BEGIN

	SET NOCOUNT ON;

	SELECT T.*, STATUS_DES 
		INTO #TESTATE
		FROM 
		COMANDA_TESTATA T WITH (NOLOCK)
		LEFT JOIN STATUS  WITH (NOLOCK)   ON STATUS = STATUS_COD
	WHERE 
			ID_COMANDA = CASE @ID_COMANDA WHEN 0 THEN ID_COMANDA ELSE @ID_COMANDA END AND
			ID_BASKET = CASE @ID_BASKET WHEN 0 THEN ID_BASKET ELSE @ID_BASKET END AND
			STATUS = CASE @STATUS WHEN '' THEN STATUS ELSE @STATUS END
	
		
		

	SELECT * FROM  #TESTATE T
	ORDER BY ID_COMANDA DESC
		
	SELECT R.* FROM COMANDA_RIGA R JOIN #TESTATE T
	ON T.ID_COMANDA = R.ID_COMANDA
	ORDER BY ID_COMANDA
	
	SET @RISULTATO		= 'OK' 
	SET @DESRISULTATO	= 'TUTTO OK'	

END