

-- ======================================================================
-- Author:		FRANCESCO TATARANNI
-- Create date: 01-09-2020
-- Description:	SELEZIONE DI TUTTI GLI ARTICOLI PRESENTI IN UN MENU
-- ======================================================================
CREATE PROCEDURE [dbo].[PRC_GET_MENU_ARTICOLO]
@ID_MENU INT,
@ID_LINGUA INT = 0
AS
BEGIN
	SET NOCOUNT ON
	SELECT A.ID_ARTICOLO, CASE WHEN @ID_LINGUA = 0 THEN NOME ELSE AL.DESCRIZIONE END NOME,
	A.DESCRIZIONE, A.ID_CATEGORIA, DEFAULT_IMAGE, PREZZO, ID_REPARTO, A.STATUS, 
	ISNULL(DESCRIZIONE_CATEGORIA, '') DES_CATEGORIA, CASE WHEN C.ORDINE IS NULL THEN 0 ELSE C.ORDINE END ORDINE, C.IMMAGINE, C.STATUS STATUS_CATEGORIA, C.VISUALIZZA,
	ISNULL(DESCRIZIONEREPARTO, '') DES_REPARTO, R.CODICE_NEGOZIO, R.DESCRIZIONECORTA, R.NOMESTAMPANTECOMANDA, R.STATUS REP_STATUS, R.VISUALIZZA,
	DECONGELATO
	FROM ARTICOLO A
	JOIN MENU_ARTICOLO MA ON MA.ID_ARTICOLO = A.ID_ARTICOLO
	LEFT JOIN CATEGORIA C ON C.ID_CATEGORIA = A.ID_CATEGORIA
	LEFT JOIN REPARTO R ON R.IDREPARTO = A.ID_REPARTO
	LEFT JOIN (SELECT * FROM ARTICOLO_LINGUA WHERE ID_LINGUA = @ID_LINGUA) AL ON AL.ID_ARTICOLO = A.ID_ARTICOLO
	WHERE ID_MENU = @ID_MENU
END