CREATE PROCEDURE [dbo].[PRC_GET_TALLONCINO]
 @NEGOZIO VARCHAR(10) = 0,
 @EAN_TALLONCINO VARCHAR(13) = 0
 
AS
	SET NOCOUNT ON
	
	SELECT *
	FROM TALLONCINO_BILANCIA 
	WHERE
	NEGOZIO  =	@NEGOZIO AND
	EAN_TALLONCINO = @EAN_TALLONCINO