
-- =============================================
-- Author:		DELPIANO
-- Create date: 08-03-2014
-- Description:	COPIA I BASKET PAGATI SULLO SCONTRINATO ED ELIMINA GLI ALTRI
-- =============================================
CREATE PROCEDURE [dbo].[PRC_BASKET_SALVATAGGIO_TOTALE]
@CODICE_NEGOZIO 	VARCHAR(10) = '',
@RISULTATO			CHAR(2)			= '' OUTPUT,
@DESRISULTATO		VARCHAR(1000)	= '' OUTPUT
AS
BEGIN


BEGIN TRY

	SET NOCOUNT ON;
	SELECT ID_BASKET, PAGATO INTO #TESTATE FROM BASKET_TESTATA WITH (NOLOCK)
	WHERE CODICE_NEGOZIO = @CODICE_NEGOZIO	
	DECLARE @ID_BASKET	INT
	DECLARE @PAGATO		CHAR(1)


	DECLARE CURBSK CURSOR FOR 
			SELECT ID_BASKET, PAGATO FROM #TESTATE WITH (NOLOCK)

	OPEN CURBSK

	FETCH NEXT FROM CURBSK  INTO  @ID_BASKET, @PAGATO

	WHILE @@FETCH_STATUS <> -1
	BEGIN

		IF @PAGATO = 'S' 
		BEGIN
			--PRINT 'SALVO e CANCELLO' + CONVERT(VARCHAR,@ID_BASKET)
			EXECUTE PRC_BASKET_TO_SCONTRINATO @ID_BASKET
		END
		ELSE
		BEGIN
			--PRINT 'CANCELLO ' + CONVERT(VARCHAR,@ID_BASKET)
			DELETE	   FROM BASKET_TESTATA   WHERE ID_BASKET = @ID_BASKET 
			DELETE	   FROM BASKET_RIGA      WHERE ID_BASKET = @ID_BASKET 
			DELETE	   FROM BASKET_PAGAMENTO WHERE ID_BASKET = @ID_BASKET  		
		END
		
		FETCH NEXT FROM CURBSK  INTO   @ID_BASKET, @PAGATO

	END
	
	EXECUTE dbo.PRC_CANCELLA_COMANDA --@CODICE_NEGOZIO, ''

    SET @RISULTATO = 'OK'
	SET @DESRISULTATO = 'BASKET INSERITO CORRETTAMENTE'

END TRY
BEGIN CATCH
    SET @RISULTATO = 'KO ' + ERROR_MESSAGE()
    SET @DESRISULTATO = ERROR_MESSAGE()
END CATCH	

	CLOSE 		CURBSK
	DEALLOCATE 	CURBSK
END