

CREATE PROCEDURE [dbo].[PRC_GET_ARTICOLObyTIPO_ARTICOLO]
 @TIPO_ARTICOLO		CHAR(1),
 @CODICE_NEGOZIO	VARCHAR(10) = ''
 	
AS
	SET NOCOUNT ON
	
	SELECT ARTICOLO.*, ISNULL(CAST(giacenza AS INT),0) as giacenza,
	ISNULL(DESCRIZIONE_CATEGORIA,'') as des_categoria
	FROM ARTICOLO
	left join GIACENZA ON GIACENZA.ID_ARTICOLO = ARTICOLO.ID_ARTICOLO 
	left join CATEGORIA ON CATEGORIA.ID_CATEGORIA = ARTICOLO.ID_CATEGORIA
	WHERE
	CODICE_NEGOZIO = CASE WHEN @CODICE_NEGOZIO = '' THEN CODICE_NEGOZIO ELSE @CODICE_NEGOZIO END AND
	TIPO_ARTICOLO = @TIPO_ARTICOLO AND ARTICOLO.STATUS = 'V'
	ORDER BY CODICE_ARTICOLO