CREATE PROCEDURE [dbo].[PRC_GET_REPARTObyID_REPARTO] 
	@IDREPARTO INT=0, 
	@CODICE_NEGOZIO VARCHAR(10)= '001',
	@DESCRIZIONEREPARTO VARCHAR(500)= ' ',
	@NOMESTAMPANTECOMANDA VARCHAR(250)= ' ',
	@DESCRIZIONECORTA VARCHAR(25)= ' ' 
	
AS
BEGIN

	SET NOCOUNT ON
	
	--SELECT *
	--FROM REPARTO  
	--WHERE  
	--@ID_REPARTO =	CASE WHEN @ID_REPARTO = 0 THEN @ID_REPARTO ELSE @ID_REPARTO END 

    SELECT  CODICE_NEGOZIO ,IDREPARTO, DESCRIZIONEREPARTO, NOMESTAMPANTECOMANDA, DESCRIZIONECORTA 
    FROM REPARTO
	WHERE
	CODICE_NEGOZIO = @CODICE_NEGOZIO AND
	REPARTO.IDREPARTO = CASE WHEN @IDREPARTO = 0 THEN REPARTO.IDREPARTO ELSE @IDREPARTO END  
END