


CREATE PROCEDURE [dbo].[PRC_GET_ARTICOLObyID_ARTICOLO]
 @STATUS VARCHAR(10) = 'V',
 @ID_ARTICOLO INT=0,
 @CODICE_NEGOZIO VARCHAR(10) = ''
AS
	SET NOCOUNT ON
	
	SELECT ARTICOLO.*, ISNULL(GIACENZA ,0) as giacenza,
	ISNULL(DESCRIZIONE_CATEGORIA,'') as des_categoria,
	ISNULL(en.DESCRIZIONE, ARTICOLO.DESCRIZIONE)  AS descrizione_en,
	ISNULL(fr.DESCRIZIONE, ARTICOLO.DESCRIZIONE)  AS descrizione_fr
	FROM ARTICOLO 
	left join GIACENZA ON GIACENZA.ID_ARTICOLO = ARTICOLO.ID_ARTICOLO
	left join CATEGORIA ON CATEGORIA.ID_CATEGORIA = ARTICOLO.ID_CATEGORIA
	left join 
	(select * from ARTICOLO_LINGUA where ID_LINGUA=2 ) as EN
	on ARTICOLO.ID_ARTICOLO= EN.ID_ARTICOLO
	left join 
	(select * from ARTICOLO_LINGUA where ID_LINGUA=3 ) as FR
	on ARTICOLO.ID_ARTICOLO= FR.ID_ARTICOLO	
	WHERE 
	CODICE_NEGOZIO = CASE WHEN @CODICE_NEGOZIO = '' THEN CODICE_NEGOZIO ELSE @CODICE_NEGOZIO END AND
	ARTICOLO.STATUS = @STATUS AND
	ARTICOLO.ID_ARTICOLO = CASE WHEN @ID_ARTICOLO = 0 THEN ARTICOLO.ID_ARTICOLO ELSE @ID_ARTICOLO END