-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[PRC_GET_SOTTOCANALEbyIDSOTTOCANALE]
 @ID_SOTTOCANALE INT = 0,
 @SIGLA_SOTTOCANALE VARCHAR(10)	= '' ,  
 @DESCRIZIONE_SOTTOCANALE VARCHAR(10)	= '',
 @COD_CANALE_VENDITA VARCHAR(10) = '' ,
 @COD_NEGOZIO VARCHAR(10)= '001' ,
 @ORA_DA VARCHAR(10) = '' ,
 @ORA_A VARCHAR(10) = ''	
AS
BEGIN
	SET NOCOUNT ON;
	 SELECT  ID_SOTTOCANALE ,SIGLA_SOTTOCANALE ,DESCRIZIONE_SOTTOCANALE, COD_NEGOZIO , COD_CANALE_VENDITA, ORA_DA, ORA_A
    FROM SOTTOCANALE 
	WHERE
	SOTTOCANALE.ID_SOTTOCANALE = CASE WHEN @ID_SOTTOCANALE = 0 THEN SOTTOCANALE.ID_SOTTOCANALE  ELSE @ID_SOTTOCANALE END  
END