
CREATE PROCEDURE [dbo].[PRC_INSERT_UPD_INGREDIENTE]
@ID_INGREDIENTE INT = 0,
@DESCRIZIONE VARCHAR(200) = '',
@RISULTATO CHAR(2) = '' OUTPUT,
@DESRISULTATO VARCHAR(1000) = '' OUTPUT
AS
BEGIN
SET NOCOUNT ON
BEGIN TRY
	BEGIN TRANSACTION

	MERGE INGREDIENTE AS TARGET
	USING (SELECT @ID_INGREDIENTE, @DESCRIZIONE) AS SOURCE (ID_INGREDIENTE, DESCRIZIONE)
	ON SOURCE.ID_INGREDIENTE = TARGET.ID_INGREDIENTE
	WHEN MATCHED THEN UPDATE SET DESCRIZIONE = @DESCRIZIONE
	WHEN NOT MATCHED THEN INSERT (DESCRIZIONE) VALUES (@DESCRIZIONE);

	SET @RISULTATO = 'OK'
	SET @DESRISULTATO = 'INSERIMENTO/AGGIORNAMENTO EFFETTUATO'
	
	COMMIT TRANSACTION

END TRY
BEGIN CATCH
	IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
	SET @RISULTATO = 'KO'
	SET @DESRISULTATO = ERROR_MESSAGE()
END CATCH
END