
CREATE PROCEDURE [dbo].[PRC_INSERT_UPD_DES_ARTICOLO]
@ID_ARTICOLO	 	  INT,
@DESCRIZIONE_INGLESE  VARCHAR(200),
@DESCRIZIONE_FRANCESE VARCHAR(200),
@RISULTATO			  CHAR(2)		= '' OUTPUT,
@DESRISULTATO		  VARCHAR(1000)	= '' OUTPUT
 
AS
BEGIN
	SET NOCOUNT ON
	BEGIN TRY

	BEGIN TRANSACTION 
	-- Descrizione Inglese
	MERGE ARTICOLO_LINGUA AS TARGET
	USING (SELECT @ID_ARTICOLO) AS SOURCE (ID_ARTICOLO)
	ON SOURCE.ID_ARTICOLO = TARGET.ID_ARTICOLO AND TARGET.ID_LINGUA = 2
	WHEN MATCHED THEN UPDATE SET DESCRIZIONE = @DESCRIZIONE_INGLESE
	WHEN NOT MATCHED THEN INSERT (ID_ARTICOLO, ID_LINGUA, DESCRIZIONE)
						VALUES (@ID_ARTICOLO, 2, @DESCRIZIONE_INGLESE);
		
	-- Descrizione Francese
	MERGE ARTICOLO_LINGUA AS TARGET
	USING (SELECT @ID_ARTICOLO) AS SOURCE (ID_ARTICOLO)
	ON SOURCE.ID_ARTICOLO = TARGET.ID_ARTICOLO AND TARGET.ID_LINGUA = 3
	WHEN MATCHED THEN UPDATE SET DESCRIZIONE = @DESCRIZIONE_FRANCESE
	WHEN NOT MATCHED THEN INSERT (ID_ARTICOLO, ID_LINGUA, DESCRIZIONE)
						VALUES (@ID_ARTICOLO, 3, @DESCRIZIONE_FRANCESE);
		
	SET @RISULTATO		= 'OK' 
	SET @DESRISULTATO	= 'INSERIMENTO/AGGIORNAMENTO ARTICOLO_LINGUA'
		
	END TRY
	BEGIN CATCH
		SET @RISULTATO = 'KO'
		SET @DESRISULTATO = ERROR_MESSAGE()
	END CATCH

	IF @RISULTATO = 'OK' 
		COMMIT TRANSACTION
	ELSE
		ROLLBACK TRANSACTION

END