CREATE PROCEDURE [dbo].[PRC_SET_INIZIO_COMANDA]
@ID_COMANDA			  INT,
@CODICE_UTENTE		  VARCHAR(30),
@RISULTATO			  CHAR(2) = '' OUTPUT,
@DESRISULTATO		  VARCHAR(1000)	= '' OUTPUT
AS
begin
SET NOCOUNT ON
BEGIN TRY

	BEGIN TRANSACTION

	UPDATE COMANDA_TESTATA SET DATA_INIZIO_EVASIONE = getdate(), CODICE_UTENTE = @CODICE_UTENTE WHERE ID_COMANDA = @ID_COMANDA 
	
	SET @RISULTATO = 'OK'
	SET @DESRISULTATO = 'INSERIMENTO EFFETTUATO CORRETTAMENTE'

END TRY
BEGIN CATCH

 	SET @RISULTATO = 'KO'
	SET @DESRISULTATO = ERROR_MESSAGE()

END CATCH

IF @RISULTATO = 'OK' 
	COMMIT TRANSACTION
ELSE
	ROLLBACK TRANSACTION
END